*** Community Categories: Public and Private (Darknets)
:PROPERTIES:
:CUSTOM_ID: public_vs_private_darknets
:END:

Despite their centralised nature, *Trackers* remain the primary peer-discovery mechanism, providing newcomers with access to active swarm participants. Based on their availability, BitTorrent communities fall into two main categories: *public* and *private* swarms.

By definition, *Public Networks* are accessible to anyone, and rely primarily on the standard Tit-for-Tat (TFT) algorithm to motivate reciprocity and keep the swarm healthy. However, their lack of restrictions makes them fundamentally vulnerable to free riding and malicious content distribution, and they are more susceptible to common P2P attacks, such as Sybil and DoS-based attacks, that target the swarm's availability and content trust.

On the other hand, {{{gls(pt)}}}, often called BitTorrent Darknets, restrict access to registered users, typically requiring an invitation from an enrolled member, which is difficult to obtain. To mitigate *free riding* {{{cite(bt_004)}}}, *PTs* enforce *{{{gls(sre)}}}* on members to establish an upload-to-download ratio above a stipulated threshold, typically ranging from 0.4 to 1.0, depending on the swarm criteria. Falling below the predefined values triggers download restrictions or targets the account for removal. Thanks to these restrictions, *PTs* can prohibit dishonest behaviour, motivating participants to always contribute back to the network, after completing a download. On top of that, many networks complement this by implementing an auxiliary scoring system that grants higher download speeds, the ability to purchase invitation codes, and other features to promote honest contribution and help maintain the swarm's health {{{cite(bt_006)}}}.

Private trackers harden the swarm through participant tracking and account-level accountability, discouraging active free-riding and malicious behaviour, despite de-anonymising their members. This maintains swarm security and reciprocity,  benefits honest peers, maintains a solid *Seeder to Leecher Ratio* (SLR), and allows everyone to share computational resources as the protocol philosophy initially intended. Additionally, it is worth noting that many private networks support additional peer-discovery mechanisms, such as *DHT* and *PEX*, which further improve performance.

Requiring peers to contribute back to the network increases the number of seeders, positively impacting download performance, but decreases the per-member sharing ratio. This decrease leads to prolonged seeding cycles, resulting in higher SLR, creating even more seeders, and slowly reducing motivation to download shared resources, a problem that the authors term *Poor Downloading Motivation*. Thus, creating a tension between contributing and leeching, undermining long-term reciprocity {{{citep(bt_006_4)}}} and sustainability.

It is of utmost importance in any BitTorrent network to maintain an appropriate SLR range to avoid the problems stated earlier. At the same time, it requires keeping a well-designed mechanism to motivate peers to contribute back to the network and achieve a reasonable SLR range. This allows the network to further scale while keeping the number of users healthy. Furthermore, the researchers {{{citep(bt_004)}}} report adopting a *Predator-Prey Model* to address the *Poor Downloading Motivation* observed among *PTs*, aiming to preserve fair SRE to maintain a healthy balance of seeders and leechers within the network.

**** The Predator-Prey Model
:PROPERTIES:
:CUSTOM_ID: predatory_model
:END:


The *Predator-Prey Model*, adapted from ecology, serves as a mathematical framework for analysing and improving the long-term sustainability of *PTs* {{{cite(bt_006)}}}. The authors map the dynamics of both *seeders* and *leechers* to the classic Lotka-Volterra equations with logistic growth for the *prey*. To account for realistic resource limits, the original model is modified to prevent unbounded exponential growth.

+ *Prey (Seeders)*:

  These are peers that provide upload capacity, back the network with already-verified chunks, and may survive independently while contributing to the network.

+ *Predator (Leechers/Downloaders)*:

  These are the peers that consume upload capacity, eventually obtaining the complete file from the network. They ideally upload already verified pieces back to the swarm, following BitTorrent's reciprocity. However, it ultimately depends on the seeder's resources to complete downloads.

This model works by incorporating three key BitTorrent mechanisms inspired by the Lotka-Volterra framework:

+ *Dependency*:

  The growth rate of *predators* is proportional to the amount of *prey*; this results in more seeders, improved download performance, and the attraction or retention of a larger number of concurrent downloaders. Conversely, the decline in prey-driven upload rate is directly proportional to the scarcity of predators. In other words, the intense consumption of available uploaded resources eventually leads to higher bandwidth saturation, demotivating seeders and causing them to cease uploading entirely when sharing ratios become significantly imbalanced.

+ *Transition*:

  Given BitTorrent's reciprocity, *predators* (leechers) will eventually convert back into *prey* (seeders) once they finish the download and start uploading back to the swarm. This conversion is crucial to maintaining the overall swarm's health, but can be delayed or reduced in *PTs* due to the high SLR explained earlier.

+ *Consumption*:

  The *leecher consumption ratio* of the network's finite resources supported by the active seeders indicates the leeching load over the network's maximum capacity. A high consumption rate overwhelms the seeder's contribution capacity, leading to slower download speeds, higher choking rates, and reduced motivation to contribute back.

It's further explained that this model defines two *critical factors* that define how scalable this system may be:

+ *Leecher Ability*:

  This represents the download efficiency, expressed as the number of seeders a single leecher needs to consume to maximise their download bandwidth.

+ *Seeder Ability*

  This is the upload capacity, expressed as the maximum number of peers (leechers) a single seeder can upload to concurrently while achieving its maximum bandwidth.

By actively simulating these dynamics, the authors {{{cite(bt_006)}}} aim to identify optimal stable SLR ranges, helping diagnose why *PTs* can become unsustainable while addressing *free riding* and designing better overall contribution mechanisms.

*** Free-Riding and Incentive Mechanisms
:PROPERTIES:
:CUSTOM_ID: free_riding_mechanisms
:END:

Free riding is the act of consuming shared resources in a BitTorrent swarm without contributing back to the network. Despite BitTorrent's built-in reciprocity mechanism, it is still insufficient to prevent this practice at scale. It is well known that many peers never actually meet the upload ratio relative to what they downloaded.

As explained earlier, BitTorrent relies on the *reciprocity principle*: downloaders (leechers) are expected to upload verified pieces to others, either while downloading or after completion, to sustain the swarm and keep propagating torrents. This mutual contribution not only keeps pieces circulating but also maintains the high availability for leechers, justifying the existence of a decentralised P2P file-sharing network. Without sufficient uploading, the overall system becomes inefficient, lowering download rates, increasing the rarest pieces, and increasing the likelihood of torrent corruption due to a lack of available pieces.

BitTorrent's native incentive mechanism is Tit-For-Tat (TFT), developed by Bram Cohen alongside the choking algorithm {{{cite(bt_001)}}}. This algorithm enables peers to choke neighbours that do not contribute back, and unchoke honest peers, directly incentivising reciprocal contribution. Optimistic unchoking acts as a middle ground, occurring periodically and unchoking random peers, potentially improving the after-bootstrap interconnection by increasing their chances of finding upload sources.

Despite the built-in mitigations, the authors highlight several exploits within modern swarms {{{citep(bt_004)}}}:

+ *Strategic Manipulation:*

  The authors note that recent studies indicate that users are no longer encouraged to keep contributing after a download completes, citing examples of dishonest clients that actively avoid contributing.

+ *Auction vs Fairness:*

  The authors point out the unfairness of the Tit-For-Tat incentive mechanism, specifically that it acts as an auction to determine which peers will be unchoked.

+ *Optimistic Unchoking Exploitation*:

  The author reports that free riders exploit this mechanism to quickly start leeching and avoid reciprocating by exploiting optimistic unchoking slots destined for newcomers.

For instance, *BitThief* and *BitTyrant* pose a major threat to reciprocity in BitTorrent, allowing participants an easy way to avoid contributing.

+ *BitThief:*

  A rogue client that never contributes any real data. It achieves high download rates by connecting with as many peers as possible, trying to maximise its own download rate.

+ *BitTyrant:*

  Another rogue client that dynamically adapts the upload rate based on its neighbours to calculate the exact minimum contribution required to maximise its download rate.

These clients degrade the swarm's *performance*, leveraging free riding and exploiting honest peers, thereby impacting the system capacity and disrupting honest participants.

*** Torrent Poisoning and Anti-Piracy Measures
:PROPERTIES:
:CUSTOM_ID: torrent_poisoning
:END:

Torrent poisoning is a deliberate attempt to degrade the performance and reliability of swarms sharing copyrighted resources. The paper {{{citep(bt_004)}}} explains it as an act of intentionally sharing corrupted data or deploying multiple attempts to try to impede inter-peer downloads. Multimedia industries and other organisations use these methods to prevent the sharing of copyrighted content on P2P rogue networks, overwhelming participants and reducing download speeds, damaging the swarm's health, and exploiting the reciprocity model.

They achieve this in several ways, such as:

+ *Deployment of dishonest clients*:

  Active deployment or usage of dishonest clients that pollute the network and swarms, attempting to decrease as much as possible the download rate.

+ *Mass-Scale Attacks*:

  Threat actors attempt to gain control over the swarm by deploying multiple rogue peers and executing a *Sybil* related attack to simultaneously overwhelm honest peers and prevent them from sharing protected resources.

According to the authors {{{citep(bt_004)}}}, mass-scale attacks aimed at preventing copyright infringement from circulating over BitTorrent swarms can provoke swarm failure. These attacks present a significant threat to the BitTorrent ecosystem. The authors complement by giving examples of clients (e.g., *Vuze* or *Transmission*) that lack the security measures to distinguish between honest and dishonest peers, becoming vulnerable and propagating corrupted data among participants.

*** Flash Crowds in BitTorrent Swarms
:PROPERTIES:
:CUSTOM_ID: flash_crowds_on_swarms
:END:

A flash crowd is a sudden, massive wave of newcomers joining a network or service. In BitTorrent, this phenomenon manifests as a rapid increase in peer arrivals to the swarm, dramatically expanding its size as a large number of concurrent clients seek to download a specific resource within the network. Flash crowds pose a significant challenge to BitTorrent swarms. The sudden influx of leechers overwhelms the upload capacity of the current seeders, leading to severe performance degradation, increased backlogs, and reduced overall responsiveness.

According to the researchers {{{citep(bt_007)}}}, these sudden surges can directly impact the download performance. More precisely, peers may experience a 7x slowdown in download rates during peak surge periods, as leechers compete for the limited pieces uploaded by the remaining seeders. Therefore, delaying contributions and preventing leechers from properly downloading, thereby delaying their transition into seeders, and finally contributing back to the network. This results in swarm starvation and accelerates performance deterioration.

Exacerbating this issue, BitTorrent core policies such as *Tit-for-Tat* (TFT) and *Rarest First* (RF) further complicate keeping up with downloading and uploading during a flash crowd event.

Researchers {{{citep(bt_007)}}} analysed millions of swarms to quantify the frequency, duration, and characteristics of *flash crowds*. They claimed that *Flashcrowds* occur in only a small fraction of swarms (0.3-2%), but because some torrents experience rapid popularity spikes, they can affect over 10 million users worldwide. They propose a dedicated BitTorrent Flashcrowd model and an additional identification algorithm that aims to classify and detect them. Their model proposes the following 4 core components to classify and identify *Flashcrowds*:

+ *Arrival Time*:

  It's the time passed between the creation of a swarm and the start of the Flashcrowd. They indicate that about 70% of major Flashcrowds start right after swarm creation, which may be due to the widespread use of automated RSS feeds.

+ *Duration*:

  Another important component is the time between user participation oscillations. They add that major Flashcrowds are indeed short-period, with an average duration of 12 hours.

+ *Plateau Period*:

  It's characterised by a stable swarm size or limited churn immediately after a sudden end to a surge. The researchers indicate that swarms tend to shrink right after the event decreases.

+ *Magnitude*:

  Finally, the magnitude is the calculated impact of the surge, based on both the *growth rate* and the swarm size increase relative to its initial size.

The authors also explore how to detect early signals by correlating swarm growth patterns with sudden flash crowds, enabling them to understand when the client must adapt its core policy implementations to prevent further damage to the network stability. Also, they use these established parameters to classify flash crowds into *Major Flash crowds*, which correspond to the largest *magnitude* values, and *Minor Flash crowds* that correspond to smaller spikes. This work highlights how a swarm can gradually grow, impact, and exploit vulnerabilities in core BitTorrent mechanisms. Additionally, modern BitTorrent mitigates this issue by offering the option to decentralise discovery with *DHT* and *PEX*, distributing the load across multiple nodes.
