*** Monitoring Distributed Trackers and DHTs
:PROPERTIES:
:CUSTOM_ID: monitoring_distributed_trackers
:END:

# (citeme: 005, read once again to check all the facts)

Previous research done on tracking user activities and how to de-anonymize them in BitTorrent swarm has often targeted centralized components like *trackers* or *bootstrap nodes* in the DHT. Which often proceed by logging peer integrations (e.g., IP addresses, requests and associated infohashes) in order to infer user behaviour and content assessment.

A simple methodology for tracking user actions, would be passively observing or simply counting peers, thus eventually getting a big picture inside of the swarm. Although, this approach could lead to low fidelity statistics. [cite] propose an advanced measurement methodology, that proposes a *Distributed Tracker Monitoring* solution, that aims to actively gather high-fidelity data that would translate into a complete snapshot of the swarm. Their primary goal is to collect detailed swarm data in order to design and evaluate the *Application Layer Traffic Optimization* (ALTO) services (standardized by IETF). This services help by providing a network aware guidance to P2P implementations, helping to reduce ISP transit consts and improving performance.

Different from basic tracking, they suggested a distributed tracker that deploys several distributed nodes controlled by a central master node, similar behaviour to botnets, that repeated query a centralized *tracker* (s) to gather a list of peers. In their experiment, the authors used 219 nodes from PlanetLab and 159 nodes from G-Lab, two different testbeds, which were controlled by a central node. These ran a modified BitTorrent clients that query trackers and collected the returned peer lists.

As typically *trackers* return only a random subset of peers, often about 50 peers in each response, rather than a full list to prevent abuse and reduce unnecessary load. A single node can only see a fraction of the swarm. To overcome this, while cover more parts of the swarm, they propose the *Coupon Collector's problem*, which is a classic probability result. The model stipulates that if there are X unique "coupons", the expected number of random samples needed in order to collect all of them is approximately X * ln(x). For a warm of approximately 20,000 peers, the authors calculated that using 219 PlanetLab nodes, each performs 20 parallel requests, would identify nearly all unique peers with a high degree of probability.

Using this distributed crawler, they manage to obtain a full swarm snapshots in about 5 minutes without overloading trackers, by spacing queries and limiting request rate on each dumb node.

Analysing the data captured by them, in tracker dependent swarms, because of the decentralised nature of *DHT* or *PEX* this approach isn't effective, almost 97.5% of the IP addresses are from movie swarms and over 98.5% are related to music swarm. Thus, successfully enumerate and record all peers within a swarm. They also, mention that the presence of dishonest or malicious peers heavily distorts snapshots, by inflating the swarm size and disrupt measurements.

This experiment has proven that BitTorrent client with centralized *trackers* can be exploited even if not malicious to de-anonymize user activities and capitalize over their actions within the network. While modern BitTorrent ecosystems mitigate some of this vulnerabilities, by favouring the adoption of DHT or PEX discovering protocols, which turn this approach obsolete. Also, providing tracker rotation, rate limiting, and on *Dark Nets* having private trackers that prevent public crawling. Thus, requiring a more sophisticated tracking.
