*** SPDY and HTTP/2
:PROPERTIES:
:CUSTOM_ID: spdy
:END:

In 2009, Google introduced *SPDY* as an experimental application-layer protocol to address performance limitations of the HTTP/1.1 protocol {{{citep(quic_001)}}}. At that time, it was widely adopted by Google servers and products, as well as by Facebook and Twitter. It operated over TCP and addressed HTTP/1.1 bottlenecks and limitations, requiring almost no modifications to web applications. Specifically, it operates by establishing TCP streams, while allowing multiplexing, prioritisation, and other improvements. Although obsolete, it influenced the development of HTTP/2, which was developed by the *Internet Engineering Task Force* (IETF).

SPDY establishes a single TCP connection (SPDY session) and handles several simultaneous requests within a single bidirectional tunnel {{{citep(quic_006)}}}, allowing either side to stream data interleaved, without blocking HTTP pipelining, thereby reducing network overhead and improving server efficiency. The protocol also offers request prioritisation, where the client can assign a priority level to streams. The server then schedules the delivery accordingly, helping reduce congestion by favouring high-priority packets over noncritical ones. Moreover, by having the server push resources before the client requests them, this process reduces latency for web pages that require many dependencies. When resources are already cached, this mechanism pushes redundant objects, wasting bandwidth. Additionally, it compresses redundant HTTP headers, reducing the transmission and serialisation latency.

# here are all aggregated 001, like google, Microsoft, and stuff
In {{{citep(quic_001)}}}, showcase performance evaluations, reporting that {{{gls(plt)}}} went up to 60% compared to HTTP/1.1. However, other independent studies found mixed scenarios with both gains and losses. Ultimately, these studies concluded that SPDY performs better than HTTP at high object counts or high RTT, thanks to its multiplexing capabilities. However, its real advantage is on low-bandwidth networks, where it performs better overall than HTTP.

Nonetheless, despite performing well in most cases, TCP's reliance limits its performance at the transport layer. TCP congestion control is essential for adjusting transmission rates, but it also impacts performance. Additionally, a TCP connection requires at least one round-trip. Complicating matters further, adding TLS encryption will add another round-trip for key exchange and authentication.
