*** Sanctuary: Multi-Enclave Extension for ARM TrustZone
:PROPERTIES:
:CUSTOM_ID: sanctuary
:END:

# (citeme: 002, sactum, Brasser et al. proposed Sanctuary in 2019)

Another TEE solution *Sanctuary*, was inspired from *TrustZone* single TEE limitation, was proposed in 2019 by [cite]. It's an implementation for *Arm processors* that aims to support multiple user enclaves without bloating the *Secure World*. On top of that, as *Sanctuary* heavily riles on *TrustZone* it also inherits many of its features, including: *world separation* into *normal world* and *secure world*, *DMA control*, *secure communication to peripherals*. While, removing third-party sensitive applications from the *secure world*. Instead, each sensitive application is isolated in *Sanctuary instances*, dedicating a physical CPU core with exclusive memory regions.

They manage to accomplish this, by exploiting the *TrustZone memory controller* feature, which assigns memory regions to only selected cores running a sensitive app for a short period of time. While the removing cores run as usual on the *normal world* and *secure world*. Moreover, *Sanctuary* allows further communication between both isolated apps and the untrusted Operating System through the *Sanctuary Library* (SL), composing an interface for interacting with system resources and other enclaves.

Despite, *Sanctuary* don't provide hardware cache partitioning* like *Sanctum*, it manages by flushing core exclusive caches during initial enclave preparation and by excluding both enclave remaining information and code from the shared level cache. Thus, protecting against software cache side-channels.

Nonetheless, *Sanctuary* addresses some of the limitations of *TrustZone* and tolerates malicious code inside enclaves, it ultimately inherits *TrustZone* vulnerabilities and relies on the configuration of the memory controller. Although, in the context of BitTorrent swarms, *Sanctuary* could serve as an interesting solution to enable multiple attestation using its enclaves on ARM based mobile and embedded devices, allowing remote attestation of individual protocol components. More precisely, evaluate *piece integrity* and *authenticity*, ensuring truthful reputation scores without compromise the entire *secure world*. Enabling a better implementation prior to its baseline implementation *TrustZone*.


