*** Performance Evaluation and Measurements
:PROPERTIES:
:CUSTOM_ID: quic_performance
:END:

Several performance studies comparing TCP, SPDY, and early QUIC implementations have measured their impact on latency, throughput, and connection overhead under different network conditions. For instance, researchers {{{citep(quic_007)}}} observed that QUIC could perform significantly worse than SPDY and TCP when downloading small web elements to construct a web page, as measured by a metric they call *{{{gls(plt)}}}*. This degradation is due to the *packet pacing* mechanism, which deliberately spreads packet transmission over time to prevent queueing clog and congestion in the receiver's buffers. While this mechanism improves fairness, it introduces delay, while TCP tends to transmit them more aggressively in short fetches. For this reason, QUIC achieved higher PLT in high-bandwidth connections and lower PLT in low-bandwidth scenarios with a large number of small objects.

Furthermore, QUIC relies on other control mechanisms, such as *FEC* and *Flow Control*, which provide substantial reliability in scenarios where packets are often lost. During testing, QUIC's packet pacing increased PLT by over 20%, a direct consequence of packet ambiguity introduced to account for loss. However, if fewer critical packets were lost, it would result in lower PLT. As a result, the researchers concluded that QUIC performs better in low-bandwidth networks with a high volume of packets, thanks to the packet ambiguity. Meanwhile, it performs worse in high-bandwidth networks with fewer packets, as redundant packet transmission introduces unnecessary overhead. Additionally, in scenarios where both endpoints already knew each other, QUIC's 0-RTT resumption feature significantly reduced latency, making QUIC 30% faster than the others {{{citep(quic_001)}}}.

Another evaluation {{{citep(quic_002)}}} used a local testbed with Docker containers to deploy isolated web servers running replicas of popular public websites, such as *YouTube*, *Orange*, and others. The authors hosted a simple web server in multiple containers, joining them into a cluster, to evaluate distributed performance. Initial results indicated that PLT nearly doubled, though in subsequent connections the impact decreased, resulting in a 400-millisecond increase in PLT. In case of HTTP/2 streams, PLT increased by five times, thereby demonstrating that QUIC is less sensitive than HTTP/2.

On mobile networks (4G vs ADSL), HTTP/2 and QUIC delivered similar results, both outperforming HTTP/1.1, but QUIC performed better, reducing PLT to around 400 milliseconds, down from 500 milliseconds.

Further tests comparing PLT across complex and simple websites showed that PLT is directly proportional to the number of web objects it must download to render the webpage. The authors report QUIC's multiplexing is most effective when fetching content from fewer concurrent servers, each time. Proving it outperforms both HTTP/2 and HTTP/1.1 in both unstable, high-latency networks and mobile networks, which are the conditions of a BitTorrent swarm. Meanwhile, on a stable, high-bandwidth network, QUIC's mechanisms, such as FEC, can degrade performance by relying on redundancy and consuming extra bandwidth to achieve lower latency.
