*** Security Analysis, Attack Scenarios
:PROPERTIES:
:CUSTOM_ID: attacks_migrations
:END:

Despite QUIC addressing several issues by running on top of UDP, it ultimately inherits its vulnerabilities. That said, performing cryptographic operations on the initial unverified handshake might be subject to two types of DoS attacks: *state overflow* and *reflective amplification*. In a state overflow attack {{{citep(quic_005)}}}, an adversary performs several full handshakes with the victim server, forcing the server to pre-allocate connection state and perform asymmetric cryptography, generating the {{{gls(scid)}}}, the connection identifier, along with its TLS certificates. During the first round-trip, an attacker leverages the fact that the client has not yet been verified, so the attacker can spoof IP addresses, ports, or SCIDs to increase the number of states on the server-side. Spoofed packets will eventually congest the server's queues, leading to rejection of legitimate user requests, resembling TCP flood attacks.

On top of that, spoofing makes backtracking difficult, though an attacker's success may depend on server state, memory limits, and rate-limiting policies. In *reflective amplification* attacks {{{citep(quic_004)}}}, an adversary starts by sending several initial packets with spoofed IP addresses to a QUIC server, which then replies with a larger initial packet and a TLS handshake, including the certificates. QUIC limits unverified responses to three times the request size. However, attackers can pad initial packets to increase amplification, posing as a legitimate optimisation to reduce delays when using full certificates. Despite this, QUIC amplification attacks are unlikely, as other protocols such as NTP and DNS suffer far more, with 500 times and 60 times {{{citep(quic_004_39)}}}, respectively. Addicionally, a certificate compression reduces the oversized replies to 1-9%. Additionally, attackers tend to reuse their existing infrastructure and must slowly adapt to new protocols to conduct these attacks.
