*** Security Analysis, Attack Scenarios
:PROPERTIES:
:CUSTOM_ID: attacks_migrations
:END:

# (citeme: 005, state overflow)
# (citeme: 004, state overflow)
# (citeme: 005, refrective amplicatifation attacks)
# (citeme: 004, refrective amplicatifation attacks)
# (citeme: 004, attacks, 39)

Despite, QUIC solving several issues by implementing on top of UDP, better security, packet flow, congestion control, ultimately inherit its vulnerabilities. That said, in order to perform cryptographic operations on the initial unverified handshake might be subject to two types of DoS attacks, as such: *state overflow* and *reflective amplification*. On State overflow attack [cite] an adversary performs several full handshakes towards the victim server, thus forcing to pre-allocate the connection state and perform asymmetric cryptography, generating the *Source Connection ID* (SCID), the connection identifier, along with its TLS certificates. During the first round-trip, an attacker leverages the fact the client is yet to be verified, so he can spoof the both IP address, ports or SCIDs to increase the number of states on server-side. Spoofed packets will eventually congest server's queues leading to reject legitimate user requests, resembling TCP flood attacks. On top of that, spoofing makes backtracking difficult, although the success of an attacker may depend on server state, memory limits, rate limiting policies. On *Reflective amplification* attacks, an adversary starts by sending several initial packets with spoofed IP victims to a QUIC server, which than replies with a larger initial packet and a TLS handshake, including the certificates. QUIC limits unverified responses to three times the request size, although attackers can pad initial packets to increase amplification, posing as a legitimate optimization for full certificates to reduce delays. Despite this, QUIC amplification attacks are not likely, due to other protocols such as: NTP and DNS suffer far more with 500 times and 60 times [39], respectively. Also, a certificate compression reduces the oversize replies to 1-9%. Additionally, an attacker normally tends to reuse their existing infrastructure and would have to slowly adapt to new protocols in order to conduct these attacks.


