** TEE (Trusted Execution Environment)
:PROPERTIES:
:CUSTOM_ID: trusted_execution_environment
:END:

Despite the policies and mechanisms implemented at BitTorrent's core, {{{gls(rf)}}}, {{{gls(tft)}}} choking, {{{gls(pex)}}} and more. Each of them provides stability and performance against some of the problems discussed in previous sections: *Free Riding* (see [[#free_riding_mechanisms][Section 2.1.10]]) and *Torrent Poisoning* (see [[#torrent_poisoning][Section 2.1.11]]). Ultimately, the protocol remains fundamentally vulnerable in open, untrusted swarms, where malicious actors can exploit its P2P nature and the complexity of authenticating peers. Attackers can exploit these issues to perform *Sybil* (see [[#sybil_attacks][Section 2.1.14]]) and *Collusion* (see [[#collusion_attacks][Section 2.1.15]]) attacks, manipulating honest peers and further propagating misleading information about themselves, gradually undermining swarm integrity by exploiting vulnerabilities in DHT implementations or by exploiting the dynamics of *Flash Crowds* (see [[#flash_crowds_on_swarms][Section 2.1.12]]) to discourage peers from relying on that swarm.

These problems stem from the lack of a verifiable *trust anchor* among peers, where each node operates independently, without a proper mechanism to verify its integrity and authenticity. This way, detecting dishonest peers and identifying advanced threats in large-scale public swarms still poses a significant challenge. To mitigate these limitations, hardware-rooted mechanisms capable of *remote attestation* and *trusted execution* are paramount for protecting against and detecting malicious or dishonest peers.

# (citeme: 002)

Hardware-rooted security mechanisms provide verifiable trust guarantees that purely software-based mechanisms cannot. This section examines the foundational concepts underlying{{gls(tee)}}}, including relevant hardware security primitives, before investigating how TEE-based attestation can promote trust and authenticity, identifying and mitigating possible vulnerabilities, as described in previous sections.

+ *Trusted Platform Modules (TPM)*:

  Regularly found on new devices, these are secure *crypto processors* bound to the individual device. They offer services like *key generation*, *key attestation*, *encryption*, and their most widely used *authenticated integrity checks*, which are typically used in *Secure Boot* functionality and serve as the Operating System trust anchor {{{citep(tee_001)}}}.

  Every {{{gls(tpm)}}} ships with a unique asymmetric key pair known as the Endorsement Key (EK), embedded by the manufacturer during production and serving as the *root of trust* {{{citep(tee_007)}}}. Note that the *EK* never leaves the *TPM* but exposes a manufacturer-issued EK certification that allows third parties to verify the *TPM*'s authenticity, which is paramount to establishing initial trust. However, it uses certified *Attestation Identity Keys* (AIKs), generated by default within the *TPM* and cryptographically bound to the *EK*, typically via wrapping. AIK enables production of signed quotes without exposing the *EK*, thus serving a major role in safeguarding the *root of trust*. Additionally, a *TPM* supports measured boot, also called *Secured Boot*, by extending Platform Configuration Registers (PCR), which are monotonic registers, with cryptographic hashes of the loaded code and configuration data.

+ *Hardware Security Modules (HSMs)*:

  An {{{gls(hsm)}}} is a dedicated, physical cryptographic computing device designed to securely generate, store, and manage cryptographic keys while enabling high-assurance cryptographic operations entirely within its protected boundary. Unlike general-purpose crypto processors, this solution provides hardened, tamper-resistant protection against physical intrusion attempts and probing, and prevents key extraction. They are typically certified to strict standards that emphasise both logical and physical attack resistance.

+ *Secure Elements (SEs)*:

  {{{gls(se)}}} are a compact, embedded alternative to traditional *HSM* that implements the same core cryptographic functionality, such as *secure key storage*, *key generation*, and the isolation of operations, directly as a co-processor integrated onto the IoT device. They are largely seen in *embedded devices*.

{{{gls(tee)}}} are described as a hardware-backed approach to secure computation, implemented as isolated execution contexts that tightly integrate with the main CPU and {{{gls(soc)}}} {{{citep(tee_001)}}}. By taking advantage of native SoC, resources that include memory encryption engines, direct access to hardware, and privileged modes enable crypto operations and protected execution on general-purpose CPUs, without needing other external modules. Additionally, TEEs are tamper-resistant and provide remote attestation capabilities, which are imperative for proving trustworthiness to third parties.

The separation kernel is the core foundation component of *TEE*. Sources indicate that it was first introduced by {{{citep(tee_002_15)}}} to allow the coexistence of systems that require different levels of security on the same platform. It achieves this by dividing the system into multiple partitions, guaranteeing stronger isolation between them, and by implementing it differently across providers.

The sources further explain that security requirements for separation kernels are described in {{{gls(skpp)}}} {{{citep(tee_002_17)}}}. Furthermore, different from traditional kernels, this separation kernel is simpler, providing both time and space partitioning:

+ *Spatial separation*: data can't be modified or read by other partitions.

+ *Temporal separation*: shared resources can't be leaked by other partitions.

+ *Control of Information*: communication between partitions happens strictly when necessary.

+ *Fault isolation*: a security breach can't mess with other partitions.

Trusted Execution Environments fall into two closely related but distinct paradigms: *{{{gls(see)}}}* and *{{{gls(drtm)}}}*.

+ *Secure Execution Environment*:

  SEEs are a component of *TEE* that does not assume trust by default, but rather provides a process environment that guarantees multiple runtime protections, such as *authenticity* (ensuring unmodified code execution), *integrity* (guaranteeing that the runtime cannot be tampered with), and *confidentiality* by preventing dynamic analysis by unauthorised applications, including the operating system.

SEE differs from *TEE* by omitting the {{{gls(rot)}}} to check the integrity and authenticity of loaded code. Additionally, it does not implement existing secure mechanisms for updating applications or securing data. The authors of this paper {{{citep(tee_001)}}} explicitly defined a *TEE* as a trust-enabled *SEE* that incorporates verifiable trust anchors via remote attestation and secure bootstrapping.

+ *Dynamic Root of Trust Measurement* (DRTM)

  A *DRTM* is a set of techniques that run specific code in an isolated environment without actively relying on potentially compromised software. The {{{gls(tcb)}}} of DRTM can run code outside the isolated environment, but it includes a small part of the main Operating System. It relies on the main system memory for runtime execution, which may be susceptible to physical attacks such as *cold boots* and *bus probing*.

  On the other hand, *TEE* resists such attacks through dedicated protected memory regions. *DRTM* imposes constraints that effectively severely limit concurrency, preventing non-secure execution until the isolation context sessions are complete, making it unsuitable for a multitasking system running non-secure applications, which could prove its effectiveness in a context where peers handle several concurrent connections, like *PEX* or *DHT*.

# (citeme: 001:[67]–[69])

Furthermore, *TEE* can simulate the functionality of previously explained hardware-trusted-environment solutions: *TPMs* and *HSMs* {{{citep(tee_001)}}}. Despite providing measures to resist the most common software attacks, by isolating code execution, separating the trusted code from the untrusted environment, it is still susceptible to physical attacks such as *side-channel attacks*.

In theory, TEE-based peers in a BitTorrent swarm can act as trust anchors, enabling remote attestation among participants to verify their authenticity and integrity. This approach would facilitate the detection of malicious peers, mitigating *Sybil nodes* by requiring an attestation that includes the *proof-of-work* as the nonce and intercepting *dishonest peers* running unverified code, thereby enforcing honest behaviour. Additionally, instead of relying on a {{{gls(pki)}}} as the trust anchor, TEE remote attestation offers a compelling decentralised alternative.
