*** Sanctuary: Multi-Enclave Extension for ARM TrustZone
:PROPERTIES:
:CUSTOM_ID: sanctuary
:END:

Another TEE solution, *Sanctuary*, inspired by the *TrustZone* single-TEE limitation, was proposed in 2019 by {{{citep(tee_002_sactuary)}}}. It is an implementation for *Arm processors* that aims to support multiple user enclaves without bloating the *Secure World*. Furthermore, as *Sanctuary* heavily relies on *TrustZone*, it also inherits many of its features, including *world separation* into *Normal World* and *Secure World*, *DMA control*, and *secure communication to peripherals*. Rather than keeping sensitive applications in the *Secure World*, they are isolated on a *Sanctuary instance* on their own physical  CPU core with exclusive memory regions.

They accomplish this by exploiting the *TrustZone memory controller* feature, which assigns memory regions to only selected cores running a sensitive application for a short period. Additionally, *Sanctuary* enables communication between the isolated apps and the untrusted Operating System through the {{{gls(sl)}}}, providing an interface for interacting with system resources and other enclaves.

Despite *Sanctuary* not providing hardware cache partitioning like *Sanctum*, it mitigates by flushing core-exclusive caches during initial enclave preparation and excluding enclave data and code from the shared last-level cache, thereby protecting against software cache side-channel attacks.

Nonetheless, *Sanctuary* addresses some of the limitations of *TrustZone* and remains tolerant of malicious code within enclaves. It inherits *TrustZone* vulnerabilities and relies heavily on a correctly configured memory controller. In the context of BitTorrent swarms, *Sanctuary* could serve as an interesting solution for enabling multiple attestation via its enclaves on ARM-based mobile and embedded devices, allowing remote attestation of individual protocol components. More precisely, evaluating *piece integrity* and *authenticity*, ensuring truthful reputation scores without compromising the *Secure World* as a whole, offering a more capable alternative to bare *TrustZone* for this use case.
