*** Security Issues and Known Attacks in TEEs
:PROPERTIES:
:CUSTOM_ID: security_attacks
:END:

# (citeme: 002, 7)

Trusted Execution Environments are often promoted as an almost-perfect solution for secure execution on devices, but as discussed, they remain subject to a range of attacks. These vulnerabilities directly threaten the *remote attestation* and *isolated execution* capabilities and exfiltrate secret keys.

# (citeme: 003, [42, 45])

For instance, the *Arm TrustZone* implementation in Qualcomm's QSEE, which is dominant on Snapdragon Android Devices, has been the target of frequent attacks. The authors {{{citep(tee_001)}}} detail several exploits, including overwriting part of the secure memory region by introducing special values {{{citep(tee_001_51)}}}. As a result, unlocks the bootloader, thus unlocking the whole device.

# (citeme: 008, [20, 43, 27, 50])

Moreover, *Intel SGX* is highly susceptible to internal leakage from *side-channel attacks* that exploit CPU caches. In some cases, the operating system can access memory within the enclave {{{citep(tee_008)}}} and infer enclave secrets by observing memory pages between enclave requests {{{citep(tee_008_58)}}}. Furthermore, research demonstrate that *SGX* can indeed be exploited by transient attacks, such as *Spectre* and *Meltdown*, to exfiltrate *attestation keys* and other *enclave secrets* from these CPUs.

# (citeme: 007, AMD SME, HyperEnclave)
# (citeme: 007, HyperEnclave, 25, 72, 74)

Other physical attacks include *cold boot attacks*, *bus snooping*, and the sniffing of physical-level data signals that carry data across components, such as *PCBs*, cables, and bus lines. Both *AMD SME* and *HyperEnclave* could be used to protect the enclave from physical attacks. In the case of *AMD SME* with memory encryption, data is encrypted between the memory buses and decrypted only within the CPU (see [[#secure_encrypted_virtualization][Section 2.3.2]]). *HyperEnclave* also mitigates some side-channel attacks that affect *Intel SGX*. Since *RustMonitor* is a software component within the framework, it processes guest page tables and page-fault events without the Operating System interfering (see [[#hyper_enclave][Section 2.3.6]]), and thus cannot perform page-table-based attacks {{{citep(tee_007)}}}. Although in its current state it is not designed to protect against *transient attacks*.

**** Side Channels Attacks
:PROPERTIES:
:CUSTOM_ID: side_channels
:END:

# [findme] need to find a citation for this!

A *side-channel attack* aims to extract sensitive information from a victim process without directly modifying or observing its execution state, without the victim being aware of a potential leakage. These attacks can be carried out in either direction (victim-to-attacker or attacker-to-victim) and categorised as *physical* or *digital* attacks, leveraging hardware and software parameters, respectively.

Furthermore, in the context of TEE, physical side channels exploit hardware-level properties, such as power consumption, electromagnetic emissions, voltage fluctuations, and activities that provoke faulty behaviour in memory or computation. On the other hand, *digital* side channels are performed at the *software* level by observing cache patterns, execution timings, and branch prediction, and by observing shared resources. Due to the isolation boundaries provided by *TEE*, they are particularly vulnerable to cache-based attacks, such as timing differences in shared L1/L2/L3 caches.

**** Transient Attacks
:PROPERTIES:
:CUSTOM_ID: transient_attacks
:END:

Beyond *side-channel* attacks, the most prominent attacks are *transient-execution attacks*, which leverage the speculative execution and out-of-order execution of modern software to find loopholes and leak or access unauthorised information.

+ *Spectre Attacks*

  *TEE* is vulnerable to *Spectre Attacks* {{{citep(spectre_attacks)}}}, attempting to trick the processor into executing speculative instruction sequences, before reverting the nominal CPU state, leaking information from the victim's memory address space.

# spectre paper citation 47

+ *Meltdown Attacks*

  Unlike *spectre attacks*, *meltdown attacks* {{{citep(spectre_attacks)}}} target out-of-order execution to leak kernel memory, rather than exploiting branch prediction. They exploit some *Intel* and *ARM* processors that allow speculative execution, bypassing memory protection. For instance, an attacker could leverage Meltdown attacks to access kernel memory from user space.

These attacks can bypass memory encryption or page-table protection, potentially leaking *attestation keys*, *enclave-protected secrets*, and protocol state.
