*** Onion Routing (Tor Project)
:PROPERTIES:
:CUSTOM_ID: onion_routing_tor
:END:

# (citeme: 001, only Onion Routing)
# speak a bit of onion routing


# Hence, no relay knows the full path, only the *guard node* knows

# (citeme: 005, only Tor, Tor [9], [10] -> 006)
# (citeme: the tor project web site)

In 2006 the nonprofit organisation *The Tor Project* [cite] was constituted to further develop on the idea of using Onion Routing with the goal of increase privacy and anonymity while browsing the Internet. Anonymous browsing is achieved by routing the user traffic through several volunteer operated nodes that are denoted as *relays*, establishing a sequence where each relay peels of one layer of encryption, learning only the previous and next hop.

More precisely, when a user is about to connect to the overlay, it chooses one *Entry Node* randomly. This node knows the user IP address, but doesn't know the final destination. Than, Tor will try to find other two suitable relays to establishing the three hop circuit, that is responsible to create the anonymous tunneling. Once the path is laid out, the public keys such as k1, k2, k3 of each relay are fetched, to sequentially encrypt user data in layers. Because, asymmetric encryption, normally *RSA* or *elliptic curve Diffie-Hellman* (ECDH), isn't ideal for encrypt large inputs, these keys are used to push AES keys securely, that will encrypt the secret through the remaining nodes. Hence, only the relay node with the matching private key can unlock the symmetric key that will be used to decrypt the secret to the next node, without being able to read its content, unless they are the *exit node*. As a result, the final node is able to view the user content, and thus forward it to the corresponding final destination. Normally, an anonymity tunnel is composed by three hops, having only one *Intermediary Node*, however *Tor* allows configuring bigger circuits, but each one impacts performance. These nodes don't know nothing about the user, only the path forward to complete the circuit.

In spite of offering strong privacy protections and anonymity, *Tor* can be exploited by leveraging the edge nodes to try to profile the user actions. For instance, both the *ISP* and *Entry Node* knows the user identity and that he is browsing through an anonymity overlay. Also, the *Exit Node* despite don't knowing the origin of the request, it can observe its contents and knows how to forward it, thus observing possible sensitive data about the user, that could be used to build a profile. Even so, *Tor* offers protection to carry over information using the anonymous circuit inside the network, a threat actor could do traffic analysis on the edge nodes to infer user actions. Still, remaining paramount to prefer *TLS* protected websites to supply private data, like *sensitive information* and *passwords*.

Additionally, in contrast to traditional web browsing using *Tor* to access the *Clear Net*, which is the traditional Internet. *Onion Services*, also referred as ".onion websites", leverage the internal network to hide services that can be only access within *Tor Network*. In contrast to normal websites, these *Onion Services* aren't meant to be public, but hidden from the general public. These are identified by the respective *onion addresses*, that are composed by their public key hash, along with the *.onion* DNS entry.

The registration of *Onion Service* starts by reaching to the nearby *relay nodes* and to define them as *Introduction Points* (IPs), masking themselves behind these relays. Adding another hop, proxying all traffic concealing the *onion service* within the Tor Network, keeping its location a secret. With this in mind, in order to a user connect over to an *onion service* it must reach out the *Onion Service Descriptor* that are stored on *Hidden Service directories* (HSDirs), that are specialized relay nodes that keep *signed descriptors*. These *Onion Services Descriptor* are a textbased files that keep a list of *relays* (IPs) and *authentication keys* that are necessary for clients find and connect over to the *Onion Services*.

# (citeme: paper, Rendezvous 5)

Than the client verifies the authenticity of the *onion descriptor* using the *public key* present on the *onion address*, thus ensuring that in fact it's a valid *onion descriptor* for the respective service. In order to connect over the *Onion Service*, it picks a random relay within the network, denoted as *Rendezvous Point* (RP) [cite], this node will conceal the user identity to the IPs. Moreover, the RP relay and IP relay will exchange details and generate a random value (nonce), that will be giving by the IP to both the RP relay and the *Onion Service* relay. Than, it will be establish an anonymous circuit, roughly with three hops, between the *Onion Service* and the *RP relay*, than both *RP relay* and *Onion Service* will send the *nonce (random value)* through the connection. Once they receive the nonce it will be verified against the secret given by the *IP*, if it matches it will be proven their trustworthiness between both and the connection it's maintained. That said, this process enables establishing a secure channel over two entities that don't know themselves keeping their identities concealed even after connection. Fixing the possible traffic analysis that could be done by edge nodes, in this case by *RP relay* and *IP relay*.
