** Anonymity Overlays and Privacy Layers
:PROPERTIES:
:CUSTOM_ID: onion_or_garlic_is_the_question
:END:

While Trusted Execution Environments (TEEs) provide strong isolation for code execution, enabling peer attestation while maintaining confidentiality and integrity of the code running on both remote and local devices. Consequently, it could help to identify modified BitTorrent clients and dishonest peers within a swarm, thereby mitigating the *Sybil* and *Collusion* attacks. However, they do not inherently protect against network-level threats such as traffic analysis and IP address correlation, which can de-anonymise participants in a swarm. BitTorrent relies on *trackers*, *DHT bootstrap nodes* or other peers (PEX). If malicious actors can easily query the protocol's metadata, such as IP addresses, peer info-hashes to link download patterns, and try to build profiles on it.

To counter these threats, BitTorrent could integrate with an {{{gls(ac)}}} overlay network that would hide IP addresses and disrupt traffic correlation. Furthermore, the following sections examine solutions that support *high-bandwidth* and *bidirectional P2P traffic* and that address the increased network latency caused by adding an overlay.

While *Tor* is excellent for low-latency web browsing and hidden services, it is not the best overlay for high-bandwidth P2P workloads. Furthermore, the Tor Project discourages the use of BitTorrent due to relay overhead {{{citep(tor_blog_project)}}}, bottlenecks at exit nodes, and possible circuit correlation, which can result in worse performance for all users. In contrast, {{{gls(i2p)}}} can be an alternative for anonymous BitTorrent downloads. Even though it is not as popular as the Tor Project, it supports native BitTorrent clients, achieves better throughput than Tor, and can run entire swarms inside the overlay without ClearNet leaks.
