*** Downsides and Vulnerabilities of Tor
:PROPERTIES:
:CUSTOM_ID: tor_attacks
:END:

# lack of hidden hidden onion services
Nonetheless nothing is perfect as explained previously *Tor* can be susceptible to traffic analysis attacks to try to de-anonymize users and try to log their activities. Even though *Tor's layer encryption* and relay hopping resist passive eavesdropping, an attacker with more skills could control both *entry node* and *exit node* and try to correlate traffic to infer participants and possible destinations. Moreover, despite *Onion Services* in theory were designed to be hidden from general public, only the few who know it's *onion address* could know of its existence and establish a connection to it. In practice that are several /search engines/ and /crawlers/ that operate within Tor network to discover and index unknown onion services. These try to enumerate addresses through brute-force, wordlist scanning, descriptor harvesting from HSDirs. As a result, many onion services are catalogued and exposed to anyone, defeating the goal of strong location privacy and anonymity for hidden services.

# attacks (citeme: paper, https://ieeexplore.ieee.org/abstract/document/9471821,  [8], [6] and [10])
Exacerbating this issue *active attacks* compromise even further the *Tor network*. While an ongoing anonymity tunnel communication, there are several keys that ensure that each relay hop is encrypted. Although an attacker can try to compromise the private key of a relay and than try to impersonate it during the key's lifetime, and eventually obtain and decrypt traffic, impacting privacy whether the key is from an *exit node*. On top of that, if a threat actor manages to exfiltrate the *Node Identity key* it can forge an *onion service descriptor* and distribute it to the directory servers, effectively replacing it for a malicious node. That said, to reduce the risk the relay must ensure a proper key rotation, which is already implemented on onion v3, to prevent compromised keys to be long controlled by threat actors.

Additionally, a threat actor could exploit the lack of exit policies in order to shut down network by using political reason leading to volunteers shutting down relays because of the pressure, thus performing *smear attacks*. Also, to achieve the same result, attackers could perform DoS attacks to overflow and take down relays. Thus, reducing the overall Tor *network capacity*, consequently decreasing anonymity due to the less available relays making traffic correlation attacks easier. In addition to this, just like *BitTorrent* modified clients, *subverted* tor clients can reduce anonymity or bypass it all together. Achieving this by distributing modified versions making it easier to perform traffic analysis upon user's actions within the network majorly harming Tor reputation.

# performance draw backs (citeme: 07)
On top of that, using Tor's anonymity overlay can seriously impact performance, because of the high usage of bandwidth and multi-hop design. That said, despite the low performance drawbacks for normal web browser it's acceptable as long anonymity and privacy prevail. Although, for intense bandwidth task, such as *file-sharing*, *video streaming* not only would greatly impact performance resulting on a very slow download rates, but it would harm all volunteer relays nodes having less bandwidth for everyone else. With this in mind, the own contributes to the *Tor Project* explicitly discourages the usage of tools like *BitTorrent*, stating that destabilizes the network.
