*** Downsides and Vulnerabilities of Tor
:PROPERTIES:
:CUSTOM_ID: tor_attacks
:END:

Nonetheless, as explained previously, *Tor* can be susceptible to traffic-analysis attacks that aim to de-anonymise users and log their activities. Even though *Tor's layer encryption* and relay hopping resist passive eavesdropping, a sufficiently resourced attacker controlling both the *entry node* and the *exit node* and try to correlate traffic to infer participants and possible destinations. Moreover, despite *Onion Services* designed to remain hidden from the general public, only those who know its *onion address* can access it and establish a connection to it. In practice, there are several /search engines/ and /crawlers/ that operate within the Tor network to discover and index unknown onion services. These try to enumerate addresses through brute-force, wordlist-based scanning, and harvesting of descriptors from HSDirs. As a result, many onion services are catalogued and exposed to anyone, defeating the goal of strong location privacy and anonymity for hidden services.

# attacks (citeme: paper, https://ieeexplore.ieee.org/abstract/document/9471821,  [8], [6] and [10])

Exacerbating this issue, *active attacks* further compromise the *Tor network*. Within an active, anonymous tunnel, each relay hop appends a layer of encryption by ciphering outbound traffic with its own symmetric key. If an attacker compromises an exit node's encryption key during its lifespan, all traffic passing through that node is exposed in plaintext, thereby de-anonymising the user. Furthermore, an attacker can forge and distribute an *Online Service Descriptor* by exfiltrating a *Node Identity Key* from an honest Onion Relay. Since version 3, relays have implemented a key rotation mechanism to mitigate compromised keys {{{citep(tor_v3)}}}.

Additionally, an attacker could use political pressure to shut down relays, exploit the lack of exit policies, and force volunteers to close relays, thereby smearing the network. Attackers rely on DoS attacks, taking down as many relays as possible, reducing the available relays, and making traffic correlation easier with fewer paths. Similar to modified BitTorrent clients, attackers can run corrupted Tor relays, reducing anonymity by logging users' interactions and harming Tor's reputation.

Using Tor's anonymity overlay significantly impacts performance due to high bandwidth usage and its multi-hop design {{{citep(tor_007)}}}, despite these drawbacks being acceptable for typical web browsing, where anonymity is the priority. For intensive bandwidth tasks, such as *file-sharing* and *video-streaming*, it is infeasible, resulting in very slow downloads and impacting other volunteers across the network. For this reason, the Tor Project explicitly discourages the use of tools such as BitTorrent, stating they destabilise the network.
