*** SPDY (HTTP/2)
:PROPERTIES:
:CUSTOM_ID: spdy
:END:

# (citeme: 001, SPDY)

In 2009, Google introduced *SPDY* as an experimental application layer protocol to address performance limitations with HTTP/1.1 protocol. At the time, it was widely adopted by Google servers and products and by Facebook and Twitter. It operates over TCP and tries to fix HTTP/1.1 bottlenecks limitations requiring almost no modifications to web applications. That said, it operates by establishing TCP streams, while allowing multiplexing, prioritization, and other improvements. Despite being obsolete it influenced HTTP/2, which was develop by the *Internet Engineering Task Force* (IETF).

# (citeme: 006, SPDY)
SPDY establishing one unique TCP connection (SPDY session) with a server, and allows multiple concurrent requests to use that tunnel without blocking HTTP pipelining, by reducing network overhead and improving server efficiency. These requests are bidirectional and can be created by either the client or the server, streaming data interleaved. Also, the protocol offers request prioritization, where client can assign priority level to streams. Than, the server schedule the delivery accordingly, helping to reducing congestion problems by favour high priority packets over noncritical packets. Moreover, improving performance by the server pushing resources before the client requests them, this lazy process reduces latency for web pages that require many dependencies. Although, when resources are already cached this mechanism will push redundant objects wasting bandwidth. On top of that, it compresses redundant HTTP headers, sending reducing the transition and serialization latency.

# (citeme: 001, SPDY)
# (citeme: 001, Google 5, microsoft 6)
# (citeme: 001, Akamai 7, Cable Labs 8)

In [cite], showcase performance evaluations, reporting that [cite] *Page Load Times* (PLT) went up to 60% compared to HTTP/1.1. Also, other independent studies found mixed scenarios with both gains and losses. Ultimately, these studies concluded that SPDY has better performance than HTTP for high object or high RTT, thanks to its multiplexing capaciblities. However, its real advantages is on low bandwidth networks, having the better overall performance than HTTP.

Nonetheless, despite performing well in most cases the TCP dependency restrains the protocol at the transport layer. That said, TCP congestion control it's essential to adjust transportation rates, but impacts the performance, also a TCP connection requires at least one round-trip. Complicating matters further, adding TLS encryption will add another round-trip for key exchange and authentication.
