*** Onion Routing (Tor Project)
:PROPERTIES:
:CUSTOM_ID: onion_routing_tor
:END:

Objectively, anonymity prevents eavesdropping and traffic analysis by keeping the message and the messenger's identity hidden. Bearing this in mind, around the 90s, the concept of *Onion Routing* was developed by researchers at the U.S. Naval Research Laboratory as a general-purpose infrastructure for anonymous communication over public networks {{{citep(tor_001)}}}. It introduced the concept of Chaum mixes and mix networks. A mix is a device that accepts fixed-sized messages from multiple sources, performs cryptographic operations on them, and forwards them to the next mix at random. This approach makes message tracking difficult, even when correlating by size or bit patterns, thereby scaling with the number of available mixes.

The most important component of an *Onion Network* is the *Onion Proxy*, which manages and establishes anonymous connections and sanitises and correctly formats data streams to comply with the *Onion Network* required format.

# (citeme: 005, only Tor, Tor [9], [10] -> 006)

In 2006, the nonprofit organisation *The Tor Project* {{{citep(tor_005)}}} was established to further develop *Onion Routing* to increase privacy and anonymity while browsing the Internet. Anonymous browsing is achieved by routing user traffic through several volunteer-operated nodes, known as *relays*, establishing a sequence in which each relay peels off one layer of encryption, learning only the previous and next hops.

When connecting to the overlay, a user randomly selects an Entry Node that knows the user's IP address but not the final destination. Tor then selects two additional relays to complete a three-hop circuit, creating the anonymous tunnel. It is worth noting that a tunnel can consist of more than three hops, increasing latency and bandwidth usage and further impacting performance.

Once the path is established, the Onion Proxy fetches the public keys of each relay, negotiates a shared AES symmetric key per hop, and sequentially encrypts the user data in layers. The encrypted payload traverses the circuit hop by hop, with each relay peeling off its own encryption layer until it arrives at the exit node, where it removes the final layer and forwards the plaintext to the final destination.

Despite offering strong privacy and anonymity, Tor exposes users to profiling at edge nodes. Both the *ISP* and *Entry Node* know the user identity and that the traffic is proxied by an anonymity overlay, and the *Exit Node* only has access to the payload and metadata to route it. Based on this, an attacker positioned at edge nodes can intercept both inner and outer Tor traffic, correlating it to de-anonymise users, thereby breaking Tor's anonymity model. Considering this, despite the anonymity offered, confidentiality is still paramount, and while browsing, a user prefers TLS-protected connections over non-secure connections for sensitive actions.

So far, the previous sections have focused on explaining how Tor can provide greater anonymity when accessing the ClearNet. However, Tor hosts its own inner network of hidden services, accessible only from within the overlay. *Onion Service*, commonly referred to as {{{mark(.onion)}}} websites, are not publicly indexed and can be accessed only by those who know their onion address. An onion address is the concatenation of the service's public key hash and the {{{mark(.onion)}}} DNS suffix.

The registration process for an *Onion Service* begins by configuring the random *relay nodes* as {{{gls(intps)}}}, using them as introductory relays to conceal the* Onion Service*'s identity within the Tor Network. To reach an Onion Service, a user must query the *Onion Service Descriptor* stored at the {{{gls(hsdirs)}}}, a set of dedicated relay nodes that keep signed descriptors. An Onion Service Descriptor is a text-based document containing the IntPs and authentication keys for onion hidden services, enabling users to establish a connection.

To connect, the client chooses a random relay to become its *Rendezvous Point* (RP) {{{citep(tor_005)}}}, thereby concealing the user's identity. The RP and the Introduction Point exchange metadata details, agree on a secret value (nonce), and then the Introduction Point shares it with the Onion Service. After agreeing on the nonce, both the Onion Service and the RP establish an onion circuit, exchange the secret value, and match it with the response. A match proves that both parties are trustworthy, establishing a secure channel between them that remains anonymous throughout the connection. Neither party knows the other's identity, yet they still managed to establish a secure channel between them, keeping their identities concealed and thereby evading traffic analysis by hiding deeper within Tor's network.
