*** Quic Performance
:PROPERTIES:
:CUSTOM_ID: quic_performance
:END:

# (citem: 001, performance)

Several performance studies comparing the protocols TCP, SPDY, and early QUIC implementations have measured their impact on latency, throughput, and connection overhead ac cross different network conditions. For instance, researchers [cite] observed that QUIC could perform significantly worse than SPDY and TCP when downloading small web elements to construct a web page, on a metric they denote as *Page Load Time* (PLT). This degradation is due to the *packet pacing* mechanism, which deliberately spreads packet transmission over time in order to prevent queueing clog and congestion in the receptor's buffers. While this mechanism improves fairness it introduces delay, wile TCP tends to transmit them more aggressively in short fetches. For this reason, QUIC got higher PLT in high bandwidth connections, and lower on low bandwidth scenarios with large number of small objects.

However, QUIC's other control mechanism, such as: *FEC* and *flow control* provided substantial resilience in scenarios where packets are loss often. Where it got a 20% over TCP's almost double increase off PLT, thanks to the ambiguous critical packages sent by QUIC, despite sending more packages less critical packages were lost, resulting on lower PLT. Ultimately, the researchers concluded that QUIC performs better in low bandwidth with high quantity of packages, taking advantage of its control mechanism, while performing worse on high bandwidth networks with fewer packages, because of the same mechanism. However, in scenarios where the connection was reestablished, QUIC's 0-RTT resumption feature proven to significantly reduce latency, making QUIC performing 30% faster than the others.

# (citeme: 002, performance)

Another evaluation [cite], used a local testbed with Docker containers to deploy isolated web servers, with replicas of public popular websites, such as *YouTube*, *Orange* and others. They, host a simple web server in solo containers and a cluster of them, in order to evaluate how would perform better where the resources were clustered or distributed across several servers. The first results indicated that PLT nearly doubled, although for the consequent connections the impact was milder achieving about 400 milliseconds of increased PLT. While on HTTP/2 connections PLT increased 5 times with the delay, which demonstrates that QUIC is way less sensitive to delay than HTTP/2. Also, on mobile networks (4G vs ADSL) HTTP/2 and QUIC delivered almost the same results both outperforming HTTP/1.1, but QUIC showing better results around 400 between 500 milliseconds of PLT. Further testing comparing the PLT over complex versus simple websites cited earlier translated into better PLT for simpler websites with less web objects to download, also the researchers related that performance degraded over 8 distributing servers over 4 servers. This results show that multiplexing mechanism implemented in QUIC it's most effective on fetching content from fewer consecutive servers. This study, demonstrated that indeed QUIC outperforms both HTTP/2 and HTTP/1.1 over unstable, with high latency or mobile networks, which are precisely most peers on a BitTorrent swarm. However, on stable, high-bandwidth networks with many small objects, FEC can limit QUIC's performance by pushing extra packages and taking more bandwidth to ensure low latency.
