*** Garlic Routing (I2P Project)
:PROPERTIES:
:CUSTOM_ID: garlic_i2p_routing
:END:

# (citeme: https://i2p.net/en/docs/overview/garlic-routing/, og garlic explanation)
# (citeme: 007, i2p explanation)
# (citeme: 005, 32, clove)
# explain the actual Dark Net

In 2003, was born the I2P (Invisible Internet Project) that was an early evolution of other anonymous networking projects, drawing inspiration from *Freenet* and early *Tor* concepts. Unlike *the Tor Project* it implements the *Garlic Routing* concept offering a more decentralized alternative than *Onion Routing* with a fairly similar design to establish secure tunnels between nodes. In order to establish a tunnel, just like *tor* it uses by default a three-hop connection, where the *garlic message* is encrypted several times with symmetric keys negotiated with tunnel peers. Than the message is sent through the inbound tunnel, and for each node removes a layer of encryption until it arrives at its destination inbound gateway. Also, the *garlic message*, it's bundled with multiple application messages.

# different from *Tor* that is based on the *Onion Routing* concept, I2P implemented *Garlic Routing* design, bundling 
# finish above
# (citeme: 005, I2P)

I2P is essentially a P2P network where every node is both client and server and it uses a distributed database that stores two types of metadata, such as:

+ *RouterInfos*:

  This comprises on contract information about the I2P participant, including its capacity, IP address, port, and its key.

+ *LeaseSet*:

  It's the information of the destination inbound tunnel

Unlike *Onion Routing*, that establish secure tunnel, with three-hop relays and accepts inbound and outbound messages encrypting messages in each layer. Instead, *I2P* tunnels are one-directional, which means data only flows in only one way, to establish bidirectional communication two tunnels are necessary, *inbound tunnel* receive incoming traffic and *outbound tunnel* send ongoing traffic. On top of that, I2P while an ongoing communication it sets two types of tunnels/channels, such as *exploration tunnel*, having roughly 0 to 2 hops and *client tunnel*, having from 3 to a maximum of 7 hops. Just like *Onion Routing* each hop adds a layer of encryption, learning only the previous and next hop. An *exploration tunnels* are low priority requests, such as querying NetDB for finding new peers, publishing LeaseSet, etc. While, *client tunnels* are tied to the specific I2P application and destination, they carry high priority information, like user information, application data. Both, tunnels require two *inbound* and *outbound* channels. As a result, for a communication between two users will be created eight tunnels, four *inbound* and four *outbound*, two *exploration* and *client* tunnels for each one. Also, unlike *Tor* where it's meant for users enter the network and use it as a masking layer to access the clear net, I2P acts as a *dark net*, where all the traffic is meant to be within the network.

# (citeme: 005, Kademlia variation [44])
# (citeme: floodfill 005 [34])

That said, to establish a connection between two peers, the user will start to advertise it's *inbound gateway*, his LeaseSet, by publishing it on to the *Network Database* (NetDB). This database is maintained by a group for special Floodfill [cite] routers, that together store a distributed hash table with information about other peers, hidden services these are identified by *routing keys, that unlike traditional Kademlia are 32 bytes keys. This are generated by an SHA256 one-way hashing function and concatenated with the current UTC data string, also this hash is updated every day at UTC+0. As a result, an attacker would need every 24 hours to redo the attack, to exfiltrate another key, thus defending against long term DHT poisoning attacks. That said, Floodfill router can be manually set on the I2P client or if a peer has a high-bandwidth capabilities can automatically become a Floodfill router after passing stability and uptime tests. Similar to BitTorrent helps network peers to find themselves and share information. After publishing his *LeaseSet* it queries the NetDB for the destination's *LeaseSet* and sends a nonce using his *inbound * that will connect to the *destination peer outbound tunnel*. Once receiving the nonce, it replies the message by forward it though is *outbound tunnel* that will connect over to the *user's inbound tunnel* completing the *nonce transmission*. Also, by including their own *LeaseSet*, a signed structure that contains all destination's inbound gateways, in the message it facilitates the receptor peer as they don't have to query NetDB again. As a result, reduces latency and as it requires less queries less opportunities for a potential metadata leakage.

# (citeme: outproxy 008)

While I2P is designed as a darknet, where all traffic is intended to remain within the overlay, it is possible to proxy it over to the ClearNet through *outproxies*. These are I2P nodes that act like an *exit node*, similar to the *tor design* it accepts the garlic routed traffic and forwards it to the regular Internet. Although, its usage is rare and highly discouraged by the maintainers, because like the *tor exit node* all traffic is in plaintext, unless its encrypted, therefore the outproxy operator can observe the ongoing traffic and breaking anonymity. On top of that, for *outproxy* maintainers there is a high risk of illegal exposure, because others use their *IP* acting on its behalf. Also, these are vulnerable to I2P blacklisting and abuse.
