*** Downsides and Vulnerabilities of I2P
:PROPERTIES:
:CUSTOM_ID: i2p_downsides_and_vulns
:END:

Nonetheless, similarly to *Tor*, it inherits the same attack vectors, such as traffic analysis, censorship {{{citep(i2p_005)}}}, and DHT poisoning attacks. Some countries ban these anonymity overlays by blocking access to I2P reseed servers, which are essential to ensure the bootstrapping process. Another widely used technique is Deep Packet Inspection (DPI), in which an attacker positions at the overlay edge to intercept network traffic for analysis. Specifically in I2P, despite obscuring its traffic and preventing payload analysis, flow analysis can still be a major threat to the network. I2P traffic can be fingerprinted by observing the first four handshakes between routers, each with a fixed length of 288, 304, 448, or 48 bytes {{{i2p_005_26}}}. Additionally, some ISPs compile blocklists of active I2P peer addresses, making it difficult to bootstrap and restricting users from connecting to the network altogether.

# (citeme: 009, 20)
# (citeme: 009, 39, 40)

Studies monitor and characterise the I2P architecture to infer client usage data, recover metadata, group clients by behaviour, and infer client usage geographic density {{{citep(vs_009)}}}. The researchers' analysis revealed a high concentration in Moscow, averaging around 648 users per hour; Saint Petersburg, approximately 309; and Munich, approximately 16. This data proves that, despite overlays, traffic analysis techniques, aggregating patterns, and similar measures, can effectively de-anonymise users. Therefore, selective DoS attacks, exploiting node selection, de-anonymising *eepsite* hosts (I2P hidden services), and combining Sybil attacks further undermine anonymity guarantees.
