*** Open Source Anonymity Networks
:PROPERTIES:
:CUSTOM_ID: other_ac
:END:

Beyond the most common anonymity overlays, such as Tor and I2P, several open-source alternatives have explored similar themes. Despite some now being inactive or obsolete, they influenced modern designs and highlighted the major issues with anonymous networks.

# (citeme: 008, jap) -> idk but is missing jap maybe
# (citeme: 008, 10)

+ *JAP or JonDo (Java Anonymous Proxy)*

  A mix network developed in Germany for web browsing with enhanced anonymity. Similar to I2P, it routes traffic through several intermediaries, called mixes {{{citep(i2p_008_10)}}}. Unlike I2P, mixes are fixed and primarily designed for web browsing on the ClearNet, and therefore do not support hidden services. Eventually, the {{{gls(bka)}}} compromised the overlay, leading to the project's shutdown.

+ *MorphMix*

  A P2P mix network where every client is a mix. It is a decentralised network designed to be as low-latency and scalable, with strong protection against realistic observers {{{citep(i2p_008_12)}}}, offering good overall performance.

+ *MUTE*

  A P2P file-sharing open-source network that focuses on anonymous distribution.

+ *AntsP2P*

  A pseudonymous P2P system that achieves anonymity by routing user traffic through a network that hides each relay's physical location from other participants.

+ *Mix minion*

  Designed for anonymous emailing, it relies on volunteers operating relays, denoted as mixes. Once a sender writes the message, the client software breaks it into fixed-size chunks to prevent size-based correlation. Then, each chunk is encrypted in multiple layers, as in other mix networks, adding a layer per mix, as in onion routing. At the *final mix*, the message is forwarded to the recipient.

These early open-source projects, despite some suffering from scalability issues, legal pressure, and a lack of a solid community, demonstrated the viability of mix networks. Mix networks introduce latency by design, prioritising strong anonymity over speed, making them unsuitable for real-time applications. In contrast, they perform very well in asynchronous communication, such as email. These limitations inspired the development of more P2P-based successors, favouring anonymity systems that would scale and perform better to provide both speed and anonymity.
