*** Comparison: Tor vs. I2P
:PROPERTIES:
:CUSTOM_ID: tor_vs_i2p
:END:

In this section, it will be compared the two most popular anonymity overlays *Tor* and *I2P*, in order to understand their differences.

# network

# ( citeme: 005,  45, 68 ?, [11, 13], tor -> 60)
# ( citeme: 005 )

Tor relies on a volunteer operated nodes to build anonymity circuits, with three-hop jumps or more if configured. Also, to difficult traffic correlation attacks it needs a significant number of active exit nodes forwarding the traffic to the ClearNet. Knowing this, *Tor* heavenly relies on its volunteers operated relays to ensure diversification and ensure the three-hop circuit to every user, attacks reduce that number can severally impact privacy. On top of that, it's design favours low latency web browsing and general-purpose anonymity, having the issue of the *exit node* observe any plaintext traffic going through it and possible have legal issues. That said, high bandwidth usage, like file-sharing, video streaming, and such will result on bad performance and harm every user on the network, being highly discouraged by the *Tor Project Maintainers*.

On the other hand, *I2P* presents itself as a fully distributed overlay where it acts like a P2P network, where a peer is both client and server to others. Also, it's peers with sufficient performance to establish unidirectional tunnels, that are explicit designed for hidden services, such as: *eepsites*, *internal trackers*, etc. Also, access to the ClearNet is allow by outproxies, but highly discouraged.

# socks and api

A practical key difference between *Tor* and *I2P* lies in their interfaces implementation, which affects the effort to build or adapt applications, to work on this overlay, such as BitTorrent.

# citeme (Privoxy)

In case of *Tor* uses the standard *Socket Secure* (SOCKS) proxy interface, with allows any application that supports it route traffic through *Tor*, commonly the web browser. More precisely, the tor client will act as a local proxy routing the configured traffic through the network. Even tough it's possible to pipe traffic through tor, the SOCKS interface is able to transmit TCP only packages, which limits the performance of some P2P protocols that benefit on UDP, for some DHT operations and extensions. Additionally, some messages may leak some metadata, including User-Agent strings, HTTP headers, unless filtered by an additional layer, for example *Privoxy* [cite].

On the other hand, *I2P* provides a native middleware API rather than a general-purpose proxy. Knowing this, applications must either be explicitly adapted to implement I2P's streaming or be designed and built with I2P integration in mind. Which  translates to a higher development const and grants a better control over the anonymity properties. For example, there are some applications like I2PSnark that were built with I2P in mind.

# citeme (009, 18, mails)

Taking both into account, SOCKS interface is compatible with nearly any proxy aware tool, including most web browsers and any BitTorrent client, if configured properly. Also, using an open source proxy like proxychains is even possible to adapt almost any application and pipe though its traffic, but it may leak sensitive data. On the other hand, I2P applications are built exclusively for the internal network usage, and some examples are Susimail and 2IpMail, which enable sending and receiving mail from the ClearNet [cite]. Also, for BitTorrent support a user could use I2PSnark.

# performance <see on other papers>
# put the rest here
# performance <see on other papers>

Another critical factor is scalability when considering anonymity overlays, taking into account for high churn, bandwidth demanding applications. Both overlays face different challenges, and both architectures solve and perform differently.

Tor's circuit based design heavily relies on volunteer operated network of relays, with some serving as entry nodes and exit routers. As the number of clients increases, network traffic will grow significantly, leading to congestion. As a result, it may cause bottlenecks. On top of that, isn't fully decentralised relying on centralised *Hidden Service directories* to query the onion descriptors to fetch the necessary metadata for connecting over to hidden services. Consequently, if enough HSDirs or authorities are compromised or overloaded it could disrupt the service directory or even inject malicious descriptors.

On the other hand, *I2P* is fully decentralised relying on a distributed database NetDB, Kademlia variant with Floodfill peers. That said, Floodfill peers maintain between them the overall database, meaning no single peer can control the topology and consensus of the network. Furthermore, its decentralised nature adds multiple targets, thus more resilience to single point of failure allowing the network scalability naturally with the user growth.

Taking this into account, a scenario where there is a high bandwidth necessity along with a high churn, Tor's reliance on a centralised directories could lead to reduce performance and congestion with swarm growth. While I2P distribution model scales along user necessity distributing load across nodes by creating specialized tunnels for inbound and outbound connections, inherently performing better for large scale, high churn P2P file sharing, where growth and high demand are paramount. On top of that, despite I2P tunnels have a default lifetime of about roughly 10 minutes and then are rebuilt, for privacy, introduces a bit of overhead. Although, for sustained bulk transfers like BitTorrent doesn't pose a major problem, but using an anonymity overlay always poses some overhead.
