* System Design & Architecture
:PROPERTIES:
:CUSTOM_ID: poc_architecture
:END:

The previous chapter identified critical limitations in the current BitTorrent ecosystem. Specifically, weak incentive mechanisms that could be exploited resulting in free-riding, vulnerability to Sybil and collusion attacks, lack of a mechanism to ensure peer trustworthiness, and susceptibility to traffic analysis. This chapter addresses these challenges by presenting a high-level design and architecture for a trust-enhanced, privacy-preserving BitTorrent client Proof-of-concept aimed at mitigating these limitations. The chapter begins by establishing a threat model that defines the threat actors and their assumed capabilities underlying the design, followed by the architectural decisions and key technology choices.

** Threat Model
:PROPERTIES:
:CUSTOM_ID: poc_threat_model
:END:

The threat model identifies a network-capable adversary operating within or around a BitTorrent swarm, capable of:

+ *Traffic analysis*

  An adversary is capable of correlating peer activity, recovering IP addresses of reached nodes, recover downloaded torrents, identifying connection patterns, access public metadata, signatures, and de-anonymize participants in general.

+ *Malicious clients*

  An adversary could introduce peers running modified clients that deviate from the protocol specification, allowing free-riding, corrupting honest peers and poisoning deployable content.

+ *DHT manipulation*

  An adversary could operate a cluster of colluding nodes to flood the Distributed Hash Table, taking control over small regions of the swarm by eclipsing honest peers, slowly corrupting DHT lookups.

+ *Passive eavesdropping*

  An adversary captures inter-peer traffic, recovering metadata within a peer swarm session.

The proposed model ignores global passive adversaries capable of monitoring all network links simultaneously and physical attacks on host hardware, unless where {{{gls(tee)}}} mitigations are discussed.

** Design Goals
:PROPERTIES:
:CUSTOM_ID: poc_design_goals
:END:

The overarching goal of this architecture is to address the main security and privacy weaknesses identified in the State of the Art while preserving acceptable performance. The proposed design is guided by the CIA triad, with the main focus on Confidentiality and Integrity. That said, the design tackles the core weaknesses discussed on the previous chapter, such as:

+ *Confidentiality*

  Within a peer swarm session, its traffic and metadata must not be exposed or recoverable by a passive observer or any other swarm participant. In order to tackle this issue, it is proposed for all QUIC's traffic be routed through I2P, replacing direct P2P connections with garlic-routed tunnels. Thus, relying on I2P to secure peer's anonymity and confidentiality.

+ *Integrity*

  In addition to ensure confidentiality, a peer should be able to verify if any participant is running a trusted, unmodified client implementation. For instance, this can be guaranteed by relying on {{{gls(tee)}}} remote attestation, and secure code execution, and piece verification, which will be further detailed in further detail in the subsequent sections.

+ *Availability and Authentication*

  Each participant must possess a cryptographically verifiable identity that is strongly bounded to a hardware or software-rooted attestation quote from its TEE. By tying the peer's session identity to a valid remote attestation quote, the system prevents impersonation attacks and along with the proof of work raises the cost of Sybil attacks during a swarm admission and along the session.

Ultimately, the integration of these three technologies creates a powerful synergy across the CIA triad. For example, I2P ensures *Confidentiality* by anonymizing the underlying QUIC's communication. On the other hand, the TEE layer delivers integrity  and authentication through remote attestation and trusted execution. This culmination restores verifiable trust within an anonymous swarm. Finally, availability is preserved through a modular and flexible design. More specifically, supporting graceful degradation, where peers can decide whether to disable I2P and fall back to direct P2P QUIC connections, or disable the TEE layer and eventually rely on standard cryptographic authentication. Overall, ensuring clients remain fully functional even when not fully compatible with the required swarm layers. While each added layer, introduces some performance overhead, keeping a modular approach maintaining usability across heterogeneous systems.

** High-Level Architecture
:PROPERTIES:
:CUSTOM_ID: poc_high_level_architecture
:END:

The proposed Proof-of-concept is structured into three composable layers that constitute the BitTorrent application. Each layer addresses one of the main design goals while ensuring each layer operates independently and as a unified stack, such as:

{{{figure(diagrams/architecture/global_arch.pdf, High level architecture of the proposed system)}}}

+ *Transport Layer*

  Different from stock BitTorrent specification, instead of relying on both TCP/UDP or uTP as the sole transport protocol. During a BitTorrent client swarm sessions, a single QUIC connection is maintained per peer, carrying a dedicated control stream for protocol signaling (DHT, PEX, BEP handshake) and multiple independent streams for each concurrent piece download. As a result, this approach eliminates head-of-line blocking issue with TCP and spreads overhead across all protocol activity for a given peer.

+ *Anonymity Layer*

  In order to ensure an anonymity layer while also keeping QUIC as the underlying protocol for BitTorrent peer interaction, all QUIC's traffic is routed through an I2P instance via a local SAM bridge using a DATAGRAM session. Notably, creating an abstraction layer that can be adapted for any protocol that integrates with a SAM client. Overall, I2P is responsible for handling garlic routing, tunnel management, and NetDB queries.

+ *Trust Layer*

  # [findme] Explain better when it's implemented

  This layer is responsible for ensuring that only authentic and honest peers are admitted into the swarm, thus mitigating Sybil and collusion attacks. By default, the strategy for mitigate this issue relies on calculating a Proof-of-Work and signed tokens by trackers and bootstrapping nodes upon swarm admission. On the other hand, by integrating trusted hardware, along with the already establish measures, at swarm admission both peers could perform remote attestation, in order to ensure both are authentic and running an unmodified and trustworthy client implementation. Although, TEE isn't very common among personal devices, this layer must be optional falling back to the standard cryptographically mechanism at software level.

This architecture integrates three complementary layers to achieve the established design goals. The following sections provide a detailed breakdown of each layer integration, including the motivation behind the chosen technologies and how they were integrated.
