** Anonymity Layer: I2P Integration
:PROPERTIES:
:CUSTOM_ID: poc_i2p_integration
:END:

# [link(sota)]
As discussed in Chapter 2, I2P is better suited for P2P networks than Tor due to its decentralised NetDB, unidirectional tunnels, and its design as an internal darknet rather than an anonymizing proxy. On top of that, Tor maintainers actively discourage the usage of BitTorrent over Tor, claiming that will harm others in the network. Nonetheless, I2P properties makes it a perfect fit for the Proof-of-concept use case, where peers communicate directly with each other rather than accessing external resources.

Although, I2P might seem a good choice for anonymity a natural question arises regarding the necessity of QUIC when I2P already provides encrypted, routed communication between peers. Despite, I2P properties solve some of these issues, it doesn't address transport-level concerns concerns such as stream multiplexing, flow control, or Head-of-line blocking. Therefore, in a way both complement each other on these matters, by  QUIC handling reliable, multiplexed transport between peers, while I2P ensures that the underlying communication remains anonymous.

In order to achieve this integration with I2P network all QUIC's traffic is handled through a local SAM bridge. Exposing a socket-based API allowing applications to interact with I2P traffic without implementing their own I2P router. Taking this into consideration, SAMv3 supports some stream types (*STREAM*, *DATAGRAM*, *RAW*, *DATAGRAM2*, *DATAGRAM3*). Stream, provides reliable order delivery, and DATAGRAM, provides unreliable unordered delivery analogous to UDP. Since QUIC is built on top of UDP and implements its own reliability and ordering guarantees, a DATAGRAM session is the correct choice to bundle QUIC's packets. For instance, using a STREAM session could introduce redundant mechanisms or even break QUIC's congestion control assumptions.

In detail, this integration is achieved by binding the quinn endpoint directly to the UDP socket exposed locally by the SAM DATAGRAM session. Upon the session establishment, a UDP socket is bound to a local preconfigured port that serves as the bridge between quinn and the I2P SAM interface. Consequently, the SAM bridge intercepts outbound UDP packets and wraps them as I2P DATAGRAM messages. Afterwards, these are forwarded to the local I2P client daemon, which connects to the real I2P network. Inbound packets follow the reverse path, i2pd delivers incoming packets to the local SAM UDP socket, and quinn intercepts and processes them, extracting the QUIC payload, required for both data and QUIC's control mechanisms. As a result, this design keeps an abstraction between the transport and anonymity layers, allowing a seamless I2P integration to be optionally disabled without requiring any modifications to the transport layer or any other component of the Proof-of-Concept.

# i2pd → why not Java router, Docker deployment
The I2P client daemon chosen for this integration is i2pd, a lightweight non-Java I2P client written in C++ implementation of the I2P protocol. It was been chosen because of it's significantly lower resource footprint and startup overhead, being suitable for programmatic deployment alongside the client. Moreover, there is an open-source Docker image enabling reproducible deployments across different environments. On top of that, for testing and simulation proposes, i2pd is deployed to serve as a single host interface towards I2P network, where all peer will establish a UDP connections to proxy their traffic over I2P. Thus, being imperative for consistent tunnel configuration across development, simulation, and production environments.

# [link(treat_mode section)]]
# [link(testbed chapter)]]

Despite providing an anonymous layer on top of QUIC, I2P introduces latency overhead that significantly impacts download performance. All things considered, this is an accepted tradeoff given the threat model established in section x and its actual impact is further evaluated in Chapter 5. Nevertheless, the client can disable I2P and use default transport layer, using QUIC's full power to achieve higher download speeds.
