** Remote Attestation: TEE Integration
:PROPERTIES:
:CUSTOM_ID: poc_tee_attestation
:END:

Until this point the previous software-level mitigations, such as: proof-of-work, signed tokens, I2P layer integration establish a computational barrier and anonymity against Sybil attacks and de-anonymization attacks, respectively. However, they don't ensure that all remote participants are playing by the rules of the swarm and in fact are using a trustworthy client implementation. In reality, a malicious peer can actually pretend that is contributing and using the provided authenticated methods, while running their own modified version, practicing free-riding, corrupting data, substituting piece, among many other attacks detailed in previous sections. Without a hardware-rooted mechanism there isn't any practical way of detecting an unverified client.

Integrating Trusted Execution Environments addresses this gap by providing a hardware-rooted remote attestation, allowing other peers to identify and attest each other and collectively promote fair play among the swarm. Hence, having the tools to cryptographically verify that a remote peer is running an unmodified client implementation and within a genuine trusted hardware, before even being admitted it into the swarm.

Within the implementation chapter, it will be demonstrated how these technologies can coexist with the established design model, combining it with both QUIC and I2P. While keeping a modular design, allowing the user to disable each feature at any moment, thus promoting a broader adoption and provide a hardware agnostic solution that can be restricted by appending security layers. Despite, software only remote peers don't support TEE, the objective is that they also must be able to verify and accept remote peers that do support TEE and such remote attestation. Keeping that in mind, in {{{mark(bqti)}}} the attestation report is requested only at swarm admission alongside the standard proof-of-work, thus ensuring both computational effort and client authenticity. As explained before, TEE participation is additive, meaning peers without hardware compatibility fall back to software implementation and still remain valid participants. Moreover, the concrete attestation flow and decentralisation trade-off are detailed in [[#impl_tee_remote_attestation][Section X.X]].
