** I2P (SAM Bridge)
:PROPERTIES:
:CUSTOM_ID: impl_i2p_sam
:END:

The usage of QUIC instead of plain TCP or UDP already solves some issues in terms of peer authenticity and integrity by applying a mandatory TLS.v3 layer on top of the original transport layer protocol (UDP). However, that is not enough to fully protect participants within a public swarm, where a malicious peer can track their movement and actions within the network and potentially de-anonymizing and track them.

As already depicted in [[#tor_vs_i2p][Section X.X]], one of the main project goals was integrating the Tor project as an anonymity overlay. However, the research pointed towards I2P being significantly better suited for P2P file sharing for the reasons discussed there. That said, routing QUIC traffic through I2P was accomplished by integrating a local SAM bridge, which is detailed in this section.

To keep the system modular and configurable, users can set their client to use either standard QUIC or I2P, by specifying a CLI flag {{{mark(bqti serve :3000 --i2p)}}} (:3000, means 127.0.0.1:3000). Upon start the client will trigger the correct routing configuration adapting its inner transport protocol, in this case intercepting the live QUIC packets and pipe them through the virtual I2P stack.

It is worth noting that, whenever using I2P, the user must first configure their preferred I2P client enabling and exposing a SAM bridge (SAM v3 recommended and tested). During the development of the proof-of-concept it was used the *ip2d* client, which by default is guaranteed to work with the current implementation.

Upon start, the client establishes a control TCP connection to the SAM bridge at the local I2P instance and negotiates a {{{mark(DATAGRAM)}}} session. Choosing a DATAGRAM session offers the underlying advantage of QUIC's features, since it already implements ordering, reliability, and congestion control on top of UDP, wrapping it a STREAM session would introduce redundant information and potentially conflicting with mechanisms. Also, the session uses a {{{mark(TRANSIENT)}}} destination, generating a new I2P identity every startup rather than storing its previous one.

The hardest challenge while integrating I2P and QUIC together was {{{mark(quinn)}}} crate, the high level QUIC protocol manipulation library, expects communication over standard UDP with IPv4 and IPv6 address, while I2P peers are identified by long base64 destination strings. To address this issue, a custom socket is injected directly into the quinn endpoint, supplying a different implementation at the socket level interface, replacing the underlying UDP layer completely. All the outbound traffic is later intercepted at the socket boundary, and the fake local IPv4 address is resolved back to its matching I2P base64 address. With the valid address, a SAM header is prepended, and the packet is forwarded to the SAM UDP port. Inbound traffic arriving from the SAM bridge with the prefixed sender's I2P destination, is stripped and mapped to a local IPv4, delivering the payload back to quinn as if it arrived from a standard UDP channel.

Mapping I2P address to local IPv4 address is handled by a destination map that stores incremental fake local address with a private range {{{mark(10.0.0.0\//8)}}}, assigning each new I2P destination to its local IPv4 counterpart. Which in practice translates into {{{mark(10.0.0.1\//4242)}}}, {{{mark(10.0.0.2\//4242)}}} and so on, using private address space as defined by RFC 1918 and generic port (4242). To enable reverse address resolution, the map is bidirectional allowing on inbound connection forward (I2P base64 destination to local IPv4) and on outbound connections (local IPv4 to I2P base64 destination). Additionally, the client handles prefix matching against shortened {{{mark(base32)}}} address and their full {{{mark(base64)}}} counterparts, ensuring that peers encountered with the shortened address, are able to resolve back the full destination without creating a duplicate entry.

By embracing this method behind a common abstraction {{{mark(NetworkEndpoint)}}} all the codebase interacts uniformly, guaranteeing that the underlying API stays the same for both networking modes. Switching between QUIC and I2P doesn't require any changes to the connection management, sustaining all implemented extensions: {{{mark(DHT)}}}, {{{mark(PEX)}}}, or {{{mark(BEP)}}} protocol layers, behind the same IPv4 layer format, with only the endpoint and resolver differing between modes.

Despite this approach provide higher anonymity guarantees it comes with a great performance overhead, taking a higher toll on download performance and peer discovering in general, slowing down significantly almost any swarm operations in comparison with standard QUIC usage. Another key consideration is how I2P handles peer admission within the network, taking a long time to establish the required garlic tunnels for an anonymous interaction. That said, the user must acknowledge these drawbacks and decide if the increased identity protection is worth the performance loss.
