** BitTorrent & DHT Security
:PROPERTIES:
:CUSTOM_ID: bt_&_dht_security
:END:

*** Monitoring Distributed Trackers and DHTs
:PROPERTIES:
:CUSTOM_ID: monitoring_distributed_trackers
:END:

Previous research on tracking user activities and de-anonymising them in BitTorrent swarms has often targeted centralised components such as *trackers* or *bootstrap nodes* in the DHT, often by logging peer interactions (e.g., IP addresses, requests, and associated infohashes) to infer user behaviour and assess content.

A simple methodology for tracking user actions would be to passively observe or count peers, thereby building a broad view of the swarm. However, this approach could lead to low-fidelity statistics. {{{citep(bt_005)}}} proposes an advanced measurement methodology that proposes a *Distributed Tracker Monitoring* solution, which aims to actively gather high-fidelity data providing a complete snapshot of the swarm. Their primary goal is to collect detailed swarm data to design and evaluate the *Application Layer Traffic Optimisation* (ALTO) services (standardised by the IETF). These services provide network-aware guidance to P2P implementations, reducing ISP transit costs and improving performance.

Unlike basic tracking, the authors suggested a distributed tracker that deploys several nodes controlled by a central primary node, similar to botnets, which repeatedly query a centralised *tracker(s)* to gather a list of peers. In their experiment, the authors used 219 nodes from PlanetLab and 159 nodes from G-Lab, two different testbeds controlled by a central node. These ran modified BitTorrent clients that query trackers and collecting the returned peer lists.

Since *trackers* return only a random subset of peers, often about 50 peers in each response, rather than a full list, to prevent abuse and reduce unnecessary load. A single node can only see a fraction of the swarm. To overcome this, to improve swarm coverage, they apply the *Coupon Collector's problem*, which is a classic probability result. The model stipulates that if there are $x$ unique "coupons", the expected number of random samples needed to collect all of them is approximately $x*ln(x)$. For a swarm of approximately 20,000 peers, the authors calculated that using 219 PlanetLab nodes, each performing 20 parallel requests, would identify nearly all unique peers with a high probability.

Using this distributed crawler, they obtain full swarm snapshots in about 5 minutes without overloading the trackers by spacing queries and limiting the request rate on each dumb node.

Based on the authors' captured data {{{citep(bt_005)}}}, in tracker-dependent swarms, the authors found that the decentralised nature of *DHT* or *PEX* was ineffective. Almost 97.5% of the IP addresses are from movie swarms, and over 98.5% are related to music swarms. Thus, successfully enumerating and recording all peers within a swarm. They also mention that the presence of dishonest or malicious peers heavily distorts snapshots by inflating the swarm size and disrupting measurements.

This experiment demonstrates that a BitTorrent client with centralised *trackers* can be exploited even if not malicious to de-anonymise user activities and capitalise on their actions within the network. In comparison, modern BitTorrent ecosystems mitigate some of these vulnerabilities by favouring the adoption of DHT or PEX discovery protocols, making this approach obsolete and also providing tracker rotation, rate limiting, and, on *Dark Nets*, private trackers that prevent public crawling, requiring a more sophisticated tracking.
