# previously on BT006

*** Security Considerations in BitTorrent
:PROPERTIES:
:CUSTOM_ID: security_bt_considerations
:END:

# (cime: 008 and last)

The authors {{{citep(bt_008)}}} evaluates these attacks against three main BitTorrent clients: *Azureus* (now called Vuze), *µTorrent*, and *BitTornado*. To conduct the following experiment, they used a modified version of the *BitTornado* client to create an instrumented attack client. Also, they developed a BitTorrent traffic analyser to monitor and quickly identify the bandwidth used by seeds, honest leechers, and threats over time.

The researchers consider two natural seed attacks that threat actors seek to reduce or ideally prevent the uploading of blocks:

+ *Bandwidth Attack*

  Adversaries exploit vulnerabilities in BitTorrent's seeding algorithm and the asymmetric nature of typical access links, such as DSL, cable, and Fibre, where upload bandwidth is significantly lower than download bandwidth. Moreover, in traditional bandwidth-first seeding algorithms, like the one used in *BitTornado*, the seed *unchokes* most *leechers*, enabling them to upload while periodically evaluating their upload rates. Every 30 seconds, the *seed* chokes the slowest unchoked *leecher* and replaces it with a randomly selected peer via an optimistic unchoking. Furthermore, in this attack, attackers join the *torrent* early and attempt to consume most of the seed's unchoke slots by performing downloads at higher rates than those achievable by honest peers. As a result, this clogs the available upload bandwidth of the seeder, eventually *starving honest leechers*.

+ *Connection Attack*

  Knowing that a seed maintains up to $x$ TCP connection slots, the sources typically indicate about 50 connections, configurable. Of these, up to $x$ are unchocked for active uploading. Knowing this, the attack aims to exhaust all available connection slots with malicious peers, preventing honest peers from establishing connections. To accomplish this, it requires early detection of the torrent and effective occupation of the slots, while maintaining connections without consuming excessive bandwidth, even when an attacker periodically downloads small amounts of data. The low bandwidth behaviour distinguishes this attack from a pure bandwidth exhaustion.

Researchers {{{citep(bt_007)}}} have conducted several experiments simulating the *Flash crowd effect*, in which 5 honest leechers were connected to a seed first. After being connected, all the adversaries launch concurrently, followed by the remaining 25 leechers. They configured the seed with 4 unchoke slots and a maximum of 59 connection slots overall. Additionally, they analysed the code and documented its connection management and state transition logic of the *Vuze* client. They demonstrated that the *Vuze* client accepts incoming requests right away, unless the connection limit is reached. On top of that, it implements a finite queue called "Discovered Peers" that may be discovered by the *tracker*, *DHT* or *PEX* through gossip. Also, if there are free slots available, *Vuze* performs "Optimistic Disconnect" by starting outbound connections with the oldest peers in its queue.

Even with relatively low bandwidth, threat actors can benefit from *Vuze*'s unchoke criteria, which prioritise peers with high download rates and low amounts of data downloaded from the seed. Low downloaded resources allow attackers to gain access to some unchoke slots. Saturating slots prevents honest leechers from maintaining active connections for more than 5 minutes and progressively disconnects them via Optimistic Disconnect, while adversaries persistently try to reoccupy available slots. Notably, even attackers may suffer occasional disconnections, but if they maintain a high reconnect rate, they further increase their dominance.

*** Tribler (BitTorrent Overlay)
:PROPERTIES:
:CUSTOM_ID: tribler_bt_overlay
:END:

A prominent solution is Tribler {{{citep(tribler)}}}, an open-source project that aims to extend BitTorrent by improving remote search and connectivity, intercommunication, and decentralisation. Introduced in 2005, this project introduces a custom overlay enabling communication among Tribler peers, along with protocols that extend remote search and torrent collection, relying on the underlying BitTorrent download engine for file sharing. Rather than keeping a shared identification across BitTorrent swarms, Tribler generates a static peer identifier derived from its public key, which also enables neighbours to verify the peer’s message authenticity. Tribler improves on the standard BitTorrent contribution mechanisms by proposing the BuddyCast protocol, in which peers exchange preference lists that track their downloaded torrents, identified by the corresponding {{{mark(info\_hashes)}}}, serving as a comparative basis against other peers' preference lists, thereby calculating the similarity between them. During the BuddyCast protocol handshake, both peers exchange their preference list, the current connected taste buddies, which are the peers that download the same torrents, along with a random number of connected peers, thereby expediting the discovery of new taste buddies through both exploitation of existing connections and exploration of unfamiliar peers. Building on public/private key peer identification, Tribler extends the torrent specification to store the seeder's public key, which the seeder uses to sign all pieces it generates; thus, each peer that receives the torrent manifest can verify the authenticity of the pieces using the same public key.

Tribler introduces a reputation system (BarterCast) {{{citep(tribler_008)}}} to improve on the underlying BitTorrent contribution mechanisms, discouraging misbehaviour within a single swarm and preventing free-riding. As such, the system achieves this by signing records of data transfers between two parties within an exchange. Each peer can build a trust graph, allowing them to evaluate contribution claims locally and thereby identify falsified reports. Thus, relying on this report, neighbours can identify which peers are honest or better suited to exchange data, accounting for their swarm reputation and favouring peers with higher reputations.

Tribler successfully extends BitTorrent by persisting peer identities, adding piece authenticity, and introducing cross-swarm accountability, although it does not provide mechanisms for peer anonymity, routing privacy, or remote attestation to guarantee others are using a verified BitTorrent client. Taking into consideration the Tribler design, this thesis aims to address these issues by leveraging a similar model for peer identification and relying on asymmetric keys stored on TEE-capable platforms to confer a higher level of trust, unlike software-only peers, which are granted a lower trust level within the swarm.
