** Trusted Execution Systems
:PROPERTIES:
:CUSTOM_ID: tee_sys
:END:

*** Sanctum: RISC-V Enclave Architecture
:PROPERTIES:
:CUSTOM_ID: sanctum
:END:

In this section, other solutions that leverage TEE primitives will be presented, with a focus on open or academic designs that address or seek to improve upon the limitations of commercial implementations {{{citep(tee_002)}}}.

# (citeme: 002, Sanctum)
# (citeme: 002, Costan et al. in 2016 [cite])

One of them is *Sanctum*, which presents itself as a framework proposed by {{{citep(tee_sanctum)}}} for the open *RISC-V* architecture. This solution adopts a threat model similar to that of *Intel SGX* and follows the same user-space enclave implementation, with architectural differences and enhanced security.

*Sanctum* draws inspiration from *SGX*, where enclaves are bundled with non-sensitive host applications running in untrusted code that invoke the enclave functions, while the untrusted Operating System handle exceptions and provide the libraries that enable integration with the enclave environment.

Unlike *SGX*, where the untrusted Operating System manages page tables, each Sanctum enclave manages its own page tables, which are stored within enclave memory, thereby preventing even the Operating System from observing faulty page patterns or from inferring access behaviour. Furthermore, *SGX* implements critical enclave functions in microcode, while *Sanctum* implements critical behaviour on a software component called {{{gls(sm)}}}. This component executes at the highest privilege level in RISC-V and acts like the core of the system's TCB. More precisely, it enables both *local* and *remote attestation*, allowing the enclave to verify its own integrity and attest to measurements before execution. Although *Sanctum* does not encrypt the enclave code or data in main memory, it provides a simple protection against DMA attacks by adding two registers in the memory controllers to allow direct access to the memory region, making unauthorised access impossible and preventing any malicious peripherals, controlled by malicious software or an operating system, from accessing enclave memory.

Furthermore, *Sanctum* enforces strong isolation, preventing the Operating system from accessing the enclave's memory and the enclave from accessing the Operating System's memory, even if they attempt to switch page tables. *Sanctum* achieves this by applying minimal hardware modifications to the {{{gls(ptw)}}} in the CPU's {{{gls(mmu)}}}. This approach blocks address translations that would map to unauthorised physical memory regions for the current execution context.

A major advantage over *SGX* and other commercial solutions is *Sanctum's* resilience against *cache-side-channel attacks*. It tries to mitigate this issue through *page colouring*, a software-to-hardware technique that partitions the shared last-level cache by assigning cache lines to individual enclaves, which, later combined with L1 cache and TLB flushing on context switches, prevents cache-based leakage in access patterns or secrets.

Despite *Sanctum* representing a remarkable step toward open-source TEE implementations on RISC-V, its approach to mitigating cache side-channels can constrain memory layout and require more careful allocation at boot time. However, it served as inspiration for other frameworks that are discussed in subsequent sections, such as *Sanctuary*.
