*** HyperEnclave: Cross-Platform Software-Based TEE
:PROPERTIES:
:CUSTOM_ID: hyper_enclave
:END:

# (007, KVM [47] and Xen [29])

*HyperEnclave* {{{citep(tee_007)}}} proposes an original approach by leveraging a hypervisor-based TEE architecture, designed to be platform agnostic and operating on different CPU vendors. Unlike *SGX*, *Sanctuary* or *Sanctum*, which are tightly coupled to the specific hardware features they run on, HyperEnclave aims to abstract the hardware and run enclaves inside a minimal, trusted hypervisor (Virtual Machine). Additionally, it provides confidential cloud computing and support for existing SGX programs with minimal code changes through the enclave SDK.

To support confidential cloud computing while being deployable on legacy servers and accounting for the rise of *ARM* and *RISC-V* servers, it provides a TEE abstraction. This is achieved through virtualisation extensions on the many platforms they support, such as AMD {{{gls(svm)}}} and Intel {{{gls(vtx)}}} for isolation. If the plataform does not support any vendor virtualisation, it supports using *TPM* for root of trust, randomness, and measurement chaining. Additionally, it supports flexible enclave operation modes to balance security and performance across multiple workloads, including *user mode*, *kernel mode*, and others.

Moreover, HyperEnclave implements a lightweight hypervisor layer built on top of Linux KVM (Kernel-based Virtual Machine), replacing critical components with its own secure equivalents to enforce enclave isolation while preserving the Linux boot and runtime environments for untrusted code. During the boot process, it extends measurements to the TPM PCR as part of the authenticated TPM quote, along with a software component (RustMonitor). This component runs in monitor mode, mapping to VMX root mode.

More precisely, the *RustMonitor* is a critical, secure component of HyperEnclave {{{citep(tee_007)}}}. It runs at the highest privilege level in monitor mode or in VMX root mode on Intel, or in SVM host mode on AMD. As the name suggests, it was written almost entirely in *Rust*, leveraging the language's features to reduce the risk of memory corruption and abstraction costs, and using *Assembly* for performance-critical operations, also constituting the core of the system's {{{gls(tcb)}}}. Furthermore, *RustMonitor* enforces strong isolation between trusted and untrusted code when running untrusted operating system components and applications in the *Normal World*. It achieves this by running untrusted code in VMX non-root mode on Intel and SVM guest mode on AMD.

Conversely, trusted application code and trusted parts of the operating system run on the *Secure World*. *HyperEnclave* allows enclaves to access privileged resources restricting access to page tables and the IDT, while maintaining strong isolation by mapping secure mode to different privilege rings, operating in ring-3 or ring-0 in VMX non-root mode or ring-3 in VMX root mode for Intel hardware. Further memory isolation is enforced by hardware-based protections in the MMU, consistent with other TEE implementations.

RustMonitor and the enclave manage their page tables and handle all page faults. This approach completely removes the untrusted Operating System from the page table management loop, thereby preventing any possible attacks in which the Operating System could observe or manipulate memory mappings.

Similar to other TEE solutions such as *Intel SGX*, HyperEnclave adopts a SIGMA-style attestation protocol for remote attestation {{{citep(tee_007)}}}. The enclave measurement is signed using RustMonitor's attestation key, resulting in an {{{gls(ems)}}}. The TPM generates a {{{mark(TPM\_Quote)}}}, which is signed by the TPM's attestation key. This quote includes PCR values that measure all components of the booting process: *CRTM*, *BIOS*, *boot loader*, *vmlinuz (kernel)*, *initramfs*, and RustMonitor (the hypervisor), completing the trust chain up to the enclave itself and the verification of the generated HyperEnclave certificate. In the case of remote attestation, the verifier receives the attestation report and validates it by comparing both measurements of the booted code and the enclave against known values, and checking the certificate chains for both the TPM quote and RustMonitor's signature.

Using *HyperEnclave* with BitTorrent swarms, leveraging its process-based model, flexible privilege modes, and hardware-agnostic design, could prove an interesting solution for peer attestation. As explained earlier, running parts of the BitTorrent components inside enclaves, such as peer attestation and chunk integrity validation, could mitigate some of the attacks described earlier. However, current implementations are limited to the x86 architecture and do not support *ARM* or *RISC-V*, despite an active community interest in such extensions. Nonetheless, *HyperEnclave* could still offer a unified attestation framework across a full spectrum of BitTorrent swarm participants. As an open-source alternative that is fully auditable at any time, it provides an ideal foundation for an academic implementation of a custom, security-enhanced BitTorrent client, enabling peer-to-peer client attestation, client authenticity testing, and chunk integrity checks, while avoiding dependence on proprietary hardware features and remaining platform-agnostic.

Beyond HyperEnclave, there are other academic and open source TEE implementations that tackle other aspects, that could enhance trust within BitTorrent swarms:

+ *Komodo* {{{citep(tee_007_35)}}}, implements an SGX like enclave protection model on TrustZone backend.

+ *Keystone* {{{citep(tee_007_49)}}}, another TEE that supports RISC-V platforms.

+ *Open-TEE* {{{citep(optee)}}} by Intel Collaborative Research Institute for Secure Computing

+ *ViMoExpress* {{{citep(vimp)}}} by Electronic and Telecommunication Research Institute

+ *TLR* {{{citep(tlr)}}} by Microsoft Research
