*** SafeKeeper: SGX-Based Password Protection with Client-Side Attestation
:PROPERTIES:
:CUSTOM_ID: safe_keeper
:END:

# (003, Some of them (e.g. [5, 11, 30]) make use of hardware-based trusted execution environments (TEEs) on the server side)

This section reviews projects and implementations built upon the *TEE* primitives discussed earlier. Instead of focusing on technical description, it details how each project leverages TEE capabilities for remote attestation, memory protection, and other trust mechanisms, thereby addressing security challenges in P2P networks. Additionally, evaluate their relevance to BitTorrent and identify possible solutions to mitigate the attack vectors discussed in previous sections.

SafeKeeper, proposed by {{{citep(tee_safekeeper)}}}, is a system designed to protect password confidentiality in web authentication against attackers, including malicious servers and sophisticated phishing attacks. At its core, SafeKeeper uses a server-side password protection service that hashes user passwords before storing them, and runs isolated code inside an Intel SGX enclave. The client-side application is integrated into the browser as an extension that performs remote attestation to verify the server-side SGX enclave's authenticity, ensuring that the server is running a secure enclave protected by the SafeKeeper password protection service, thereby establishing a secure channel between the client browser and the server.

Unlike traditional approaches, SafeKeeper does not rely on TLS certificates or any other client-server protections. Once a user detects the SafeKeeper client-side signal, they can be certain that the server is running the password-hashing mechanism within an isolated TEE-attested environment and providing cryptographic proof of its integrity and authenticity, thereby protecting against both compromised servers and phishing attacks. The enclave ensures that sensitive operations cannot be observed or accessed by any untrusted software, including the Operating System, the Hypervisor, or malicious software, thereby relying on Intel SGX as a trust anchor.

Furthermore, it modifies the SGX protocol to achieve 0-RTT attestation on browsers. More precisely, when the browser requests a quote without authenticating with the enclave, it relies on a *custom attestation proxy* to cache the IAS quote verification response, thereby reducing latency. Also, it removes the TLS requirement for IAS remote attestation by delegating the verification to the proxy, allowing the browser to attest the enclave without establishing a direct TLS connection to the IAS.

*SafeKeeper* targets web authentication, trying to impede phishing attacks and malicious servers from capturing secrets. It's a client-side attestation model that focuses on verifying code integrity executed on the server side, which perfectly fits the BitTorrent threat model. Rather than attesting to a password-hashing algorithm as SafeKeeper does, a similar mechanism could attest to the proof-of-work algorithm itself, allowing a bootstrap node to verify whether the proof was computed within a trusted environment and proving that the node is running an unmodified BitTorrent client, thereby mitigating *Sybil attacks*. Enforcing TEE-based admission, along with PoW calculation, makes Sybil attacks significantly more expensive, requiring an attacker to compromise hardware-rooted trust or to expend more computational power to circumvent the admission challenges, thereby making it computationally infeasible to eclipse the swarm.
