*** WATZ: Trusted WebAssembly Runtime with Remote Attestation for Arm TrustZone
:PROPERTIES:
:CUSTOM_ID: watz
:END:

# (008, twine 27, 28)
# (008, acc tee 34)
# (008, selamda tee 35)

WebAssembly can also be integrated with Trusted Execution Environments, with some implementations using it, such as *TWINE* {{{citep(tee_008_27)}}}, an embedded trusted runtime for WebAssembly. It relies on the WebAssembly Micro Runtime (WAMR {{{citep(tee_008_28)}}}), which enables running WASM applications inside *SGX* enclaves and using its libraries to interact with the secure filesystem. Other solutions are *AccTEE* {{{citep(tee_008_34)}}} and *SeLambda* {{{citep(tee_008_35)}}}, both running WASM binaries in Intel SGX enclaves using the V8 JavaScript engine. Comparing the two solutions, SeLambda deploys serverless functions, while AccTEE provides trusted resource accounting. Unlike these solutions, *WATZ* uses *Arm TrustZone* as its TEE backend and *WASI* for system-level manipulation.

*WATZ* enables a simpler way for a *WASM application* to be executed inside the *Secure World*, without being signed, enabling third-party applications to run in a trusted environment. WATZ consists of an attester, a TEE-hosted WASM runtime, and a verifier. When a WASM application loads from the *Normal World* into the *Secure World*, WATZ copies the bytecode to *secure memory*, attests it, and runs it.

WATZ is a trusted runtime for running *WASM Applications* with *remote attestation capabilities* on an *ARM TrustZone* backend. It provides a lightweight remote attestation system to address the lack of built-in attestation mechanisms for running WASM applications in TrustZone. The developers implemented the attestation process by developing a new kernel module for the TEE, using a lightweight, embedded runtime WAMR {{{citep(tee_008)}}}, which is ideal for the TEE's required smaller footprint.

It implements a secure sandbox to isolate and prevent vertical privilege escalations and lateral attacks. Leveraging the trust chain on the boot process ensures that the WATZ code is not tampered with and is authentic. Then, upon loading a WebAssembly application, WATZ stores its bytecode in a secure memory region and measures it by hashing its signature. This hash value, along with the hardware secret, can be used by WATZ to generate the quote, enabling a third party (verifier) to attest that it is a genuine WebAssembly application running in a TEE-based environment.

WATZ offers a great advantage over other TEE solutions by running bytecode and supporting WASI, removing the constraint of C-only development. Developers can use any programming language that compiles to WebAssembly, with WASI abstracting away the underlying TEE interface.

By leveraging WATZ, WebAssembly applications execute at runtime inside TrustZone. Due to the memory sandboxing inherited from WASM, malicious applications loaded into WATZ cannot compromise the Secure World or access resources from other applications. Despite WASM's sandbox providing a safe, isolated environment for running host software, any zero-day vulnerabilities could be exploited, leading to the leakage of sensitive data or the execution of arbitrary code.

WATZ is quite relevant for BitTorrent implementations on mobile or embedded ARM devices. Rather than a native implementation, WATZ could enable a full BitTorrent client compiled to WebAssembly running specific sensitive code within TrustZone, thereby combining hardware attestation and language flexibility. However, WASM's performance overhead and WASI's networking limitations make a production-ready deployment challenging, even though it could mitigate some of the BitTorrent vulnerabilities presented earlier, such as peer attestation and piece verification. Since many mobile devices natively support WebAssembly and have access to TrustZone, this could enable a future extension allowing remote attestation of WASM modules directly in the browser, contributing to web-based BitTorrent clients.
