*** BITE: Privacy-Preserving Lightweight Clients using Trusted Execution
:PROPERTIES:
:CUSTOM_ID: bite
:END:

BITE, proposed in {{{citep(tee_009)}}}, is a solution for a Bitcoin lightweight client that delegates most of the computational and storage requirements to full blockchain nodes. As the paper explains, Bitcoin offers a private way to issue payments without being tracked by a centralised authority. However, it requires the bitcoin user to download and process the entire chain, which can be infeasible on devices with limited resources, such as mobile and embedded devices.

However, delegating to full nodes can leak critical information about the client's transactions, thereby undermining the user privacy that decentralised cryptocurrencies should guarantee. BITE addresses this by using Trusted Execution Environments, leveraging Intel SGX enclaves that serve transaction confidentiality requests from clients, since SGX provides confidentiality and integrity for client requests. More precisely, a client needs to verify a transaction or check how many coins are associated with a user's address, and it can connect to a full node which supports the BITE service.

The lightweight client establishes a secure channel with the enclave and performs *remote attestation*. Once the channel is established, the client sends the address it wants to query. Then, the enclave is responsible for gathering the required information from its locally stored blockchain or the {{{gls(utxo)}}} database and returning it to the client for verification.

Its core idea is to rely on attested enclaves on nodes with higher computational power to provide privacy and verifiable responses to lightweight clients, mapping directly to BitTorrent for mobile, embedded, or low-resource peers within a swarm. BITE enables a full blockchain node to run SGX enclaves that attest to the integrity of its code, enabling it to verify whether a transaction is valid without leaking unrelated data. A lightweight client, such as a mobile device, could perform *remote attestation* against a BitTorrent *tracker* or a DHT *bootstrap node* to verify its honesty, ensuring it isn't a modified implementation.

While BITE indeed depends on *Intel SGX*, its attestation outsourcing model is hardware-agnostic. For instance, a future BitTorrent implementation could adopt a similar model alongside other solutions, such as *HyperEnclave*, which supports both *Intel* and *AMD*-based servers. Additionally, for *Arm devices*, WATZ could be a viable option for web-based BitTorrent implementations. Contrastingly, another optimal solution would be the use of both *Sanctum* and *Sanctuary*, two open-source solutions that aim to support the rising RISC-V and x86 architectures, respectively, as well as *Arm* architectures. A unified attestation framework that abstracts these backends could support a full spectrum of BitTorrent participants, mitigate dishonesty, and uphold the BitTorrent reciprocity principle.
