** Bit Torrent

P2P networks can be the solution to improve the user space privacy, and a way to users fight back against lack those whom try to de-anonymize their fingerprint online. And, this technology has been proven over and over, being used in telecommunications, like *Matrix* and it this case in file-sharing like *Bit Torrent*, providing ways for them to share media resources, without being tracked or take down.

In this section, I will highlight how *Bit Torrent* actually works, how it can be used, which are vulnerabilities that can jeopardize both the network and de-anonymize contributors.

*Bit Torrent* is one of the most used technologies on the context of *P2P (Peer-to-Peer) content distribution networks*. According to Bit Torrent Protocol specification (citeme), it presents an advantage over plain HTTP were multiple downloads can happen concurrently for the same file, safeguarding against one HTTP Server handling multiple requests. In simple terms, it works by downloaders upload to each other the "chunks" or "pieces" that they possess to the network, making it possible to spread parts of its file across many peers, distributing the load of the HTTP operation.

This network all peers are contributors that can be identified by following *entities*:

+ *Downloaders (Leechers)*:

  These are *peers* with incomplete copies of a given file (less than 100%). Normally, they try concurrently download missing *chunks*, while positively uploading another *chunks* that were already verified to the swarm. The terminology "*leecher*" in some context it carries some negative connotations, which mainly refers to peers that only download without adequately uploading in return, which violates the reciprocity principle that BitTorrent it's built on. This actually harms the network, as its breaks the balance between *seeders* and *downloaders*.

+ *Seeders (Uploaders)*:

  These are *peers* that have 100% of the file, and normally only upload to others. Normally, are dedicated "server" peers that have the complete copies of the shared resources. This means it always must exists at least one *seeder* in order for a torrent to remain viable. Without this assurance, there isn't any guarantee that a newcomer to the network can effectively fetch all *pieces* of a *torrent*. *Seeders* are critical for a swarm health and longevity.

