*** Torrent File Specification

Before any peer can join the *swarm* (the group of peers sharing a specific file or set of files), it needs to know on how to interact with the *BitTorrent* network and locate the desired content. To achieve this, it relies on a *Metadata File*, that is also known as *.torrent*. The *.torrent* file is encoded using *Bencoding*, a simple, binary-safe serialization format designed specifically for Bit Torrent. It basely supports four data types:

  + byte *strings*, which are length-prefixed base ten, separated by a colon and the value. Like: 4:spam:corresponds

  + *integers*, that are represented by an *'i'*, then by a number in base 10, followed by an 'e'. Like: *'i3e'*

  + *lists*, that resembling the previous ones, are represented by an *'l'* followed by the respective elements encoded also in *bencoding*. Like: l4:spam4:eggse

  + *dictionary*, these are encoded by an initial *'d'* followed by the list of alternating keys and their respective values. Like: d3:cow3:moo4:spam4:eggse


The entire metadata file is a single *bencoded dictionary* containing the essential information about the swarm, which includes:

*Metadata* about the shared file(s):

  + *Announce*: it holds the URL of the tracker

  + *Info*:

    + *name*: UTF-8 encoded string, that normally stores the name of the file(s) or directory. But is only visual

    + *piece length*: it's a map to the number of bytes in each piece. Normally, files are split into fixed-size chunks in order to be downloaded in stream, this section holds the fixed-size for each piece, with the exception of the last that may be truncated. Its value is almost always, 2 ^ 18 = 256 K.

    + *pieces*: it's a map that keeps record of the chunk SHA-1 hash, that corresponds to the index. This facilitates both pieces of identifying and fetching the pieces inside the swarm, and to verify the integrity of the file(s).

    + *length*: this key is only used, when the download is one file. Also, it maps the length of the file, in bytes.

    + *files*: in case of be more than one file, this key is used.

    + *path*: it represents a list of UTF-8 encoded strings that corresponds to subdirectories names, which the last is the actual filename. Which means that a *zero length* list represents an error.


*** Peer Connections

Taking a deeper insight inside of Bit Torrent's *peer protocol*, we can observe that it operates over *TCP* or *uTP*. Also, peer connections are *symmetrical*. Which means, that *messages* sent in both directions look the same. The peer protocol checks the look up table stored inside of the metadata file, *.torrent*, and selects the pieces by their index, starting at zero. When one finish downloading a piece and checks that the hash matches, it than announces it to its peers.

**** uTP

BitTorrent clients typically communicate with trackers using HTTP over TCP, following a specified *Peer Discovery Mechanism*available on the *metadata file* (.torrent). However, this approach isn't ideal and brings significant protocol overhead.

# (citeme: utp 010)

At the Ethernet layer, each packet carries about 14 bytes of overhead, at IP layer about 20 bytes, at the TCP layer about 20 bytes and then an additional overhead at the Application Layer (HTTP). For example, a typically request and response, like a tracker queries to return a list of peers, accordingly [cite] requiring about 10 packets and roughly 1206 bytes in total.

By switching over to a UDP-based protocol will substantially decrease overhead. As a UDP tracker protocol, uses only 4 packets and approximately 618 bytes for a similar operation, thus achieving a reduction of about 50% in overall traffic volume. For an individual clients, this ends up saving roughly 1 KB per hour which is almost nothing. However, as *trackers* serve millions of peers, then manage a load reduction of about 50%, highly improving performance per peer.

Moreover, a *UDP based* protocol doesn't need connection establishment, tear down, and complex parsing of HTTP headers. This approach simplifies tracker implementation, requiring less code, reduces CPU and memory demands, and improves overall performance and scalability. On the other hand, UDP is an unreliable, connectionless protocol that lacks a builtin retransmission's of packages and congestion control features, that are present in TCP. Because of this, the application layer must implement these features itself, and audit reliability and fairness oversharing bandwidth.

**** Connection State

# (citeme - 001_torrent)
Moreover, each connection contains two bits of state in either end:

  # maybe interconnect to chocking algorithm
  + *Choked*: Which is a notification, that effectively indicates that no further data will be sent until the unchoking process happens. Knowing this, Data transfer takes place whenever one side is interested and the other side is not chocking.

  + *Interested*: Interest state must be keep up to date at all times. Whenever a downloader doesn't have something they currently would ask a peer for in unchoked, they must express lack of interest, despite being choked. Despite being tricky t implement, makes it possible for *downloaders* to know which peers will start downloading immediately after being unchoked.

  Once a connection is started by a peer, it starts out choked and not interested. Then, when data is being transferred, *downloaders* should keep several piece request queued up at once in order to get good *TCP performance*, this process is called *pipelining*. On the other side, requests which can't be written out to the TCP buffer immediately should be queued up in memory rather than kept in an application-level network buffer. So they can all be thrown out when a choke happens.

**** Pipelining and Performance

# maybe not put his, it feels not that important, or could be an image or code
  The ongoing peer wire protocol consists of a handshake followed by a never-ending stream of length-prefixed messages. The handshake starts with character nineteen (decimal) followed by the string 'Bit Torrent protocol'. The leading character is a length prefix, put there in the hope that other new protocols may do the same and thus be trivial distinguishable from each other.

  All later integers sent in the protocol are encoded as four bytes big-endian.

  After the fixed headers come eight reserved bytes, which are all zero in all current implementations

  Next comes the 20 byte SHA1 hash of the bencoded form of the info value from the metainfo file. (This is the same value which is announced as info_hash to the tracker, only here it's raw instead of quoted here). If both sides don't send the same value, they sever the connection. The one possible exception is if a downloader wants to do multiple downloads over a single port, they may wait for incoming connections to give a download hash first, and respond with the same one if it's in their list.

  After the download hash comes the 20-byte peer id which is reported in tracker requests and contained in peer lists in tracker responses. If the receiving side's peer id doesn't match the one the initiating side expects, it severs the connection.

  That's it for handshaking, next comes an alternating stream of length prefixes and messages. Messages of length zero are keepalives, and ignored. Keepalives are generally sent once every two minutes, but note that timeouts can be done much more quickly when data is expected.
# maybe not put his, it feels not that important, or could be an image or code


