*** HyperEnclave: Cross-Platform Software-Based TEE

# consider
  # *HyperEnclave* on commodity AMD servers and deployed the system in a world-leading FinTech company to support real-world privacy-preserving computations.
# consider

# (007, HyperEnclave)

*HyperEnclave* [cite], proposed in takes an original approach by leveraging a hypervisor based TEE architecture, designed to be platform agnostic and operating on different CPU vendors. Giving the previous examples, unlike *SGX*, *Sanctuary* or *Sactum* which are tightly coupled to the specific hardware features that run in, HyperEnclave aims to abstract the hardware and run enclaves inside a minimal trusted hypervisor (Virtual Machine). Also, they provide confidential cloud computing and supports for existing SGX programs with minimal code changes through the enclave SDK.

In order to support confidential cloud computing while being deployable on legacy servers and taking into account the rising of *ARM* and *RISC-V* server, their design provides a process TEE abstraction. They, achieved this by using virtualization extension on the many platforms they support, such as: AMD *Secure Virtual Machine* (SVM) and Intel *Virtualization Technology* (VT-x) for isolation. Also, *TPM* for the root of trust, randomness, and measurement chaining. Additionally, it is supported flexible enclave operation modes, in order to balance security and performance under multiple workloads, supporting *user mode*, *kernel mode* and others.

Moreover, HyperEnclave is implemented as a lightweight hypervisor layer built on top of Linux KVM (Kernel based Virtual Machine). It replaces parts with its own secure components to enforce enclave isolation, while preserving Linux boot and runtime environment for untrusted code. On the boot process it launches with the measurement extended to the TPM PCR as part of the authenticated TPM quote a software component (RustMonitor). This component runs in monitor mode which is mapped to VMX root mode.

# (007, KVM [47] and Xen [29])

More precisely, the *RustMonitor* is a critical secure component of HyperEnclave, it runs at the highest privilege level in monitor mode, or in VMX root mode on Intel or SVM host mode in AMD. As the name suggest, it was written almost entirely in *rust*, thus leveraging the languages features, meaning lower risk of memory corruption and less abstraction cost, and some parts in *assembly* for performance critical operations. Also, it constitutes the core of the system's *Trusted Computing Base* (TCB). On top of that, *RustMonitor* enforces strong isolation between the trusted and untrusted code, while providing an execution environment for nonsensitive code, by running the untrusted parts of the operation system and applications inside of the *normal world*. It achieves this, by abstracting through VMX non-root mode for Intel and SVM guest mode for AMD. On the other hand, trusted application code and trusted parts of the operating system run on the *secure world*. Also, *HyperEnclave* allows enclaves to access privileged resources, restricting access to page tables, or IDT, while maintain strong isolation by mapping the secure mode to different privileges rings. These can be ring-3 or ring-0 in VMX non-root mode or ring-3 in VMX root mode for Intel hardware). Further memory isolation is enforced by hardware based protections in the MMU like the other solutions.

HyperEnclave adopts a secure design by RustMonitor and the enclave itself managing the enclave's page tables and all page fault handling themselves. This approach completely removes the untrusted Operating system from the page table management loop, thus discarding any possible attacks where the operation system could observe or manipulate memory mappings.

Similar to other TEEs solutions like *Intel SGX*, HyperEnclave adopts a SIGMA style attestation protocol for remote attestation. With this in mind, the enclave measurement is signed using the RustMonitor's attestation key, which constructs am Enclave Measurement Signature (EMS). Also, the TPM generates a TPM_Quote signed by the TPM's attestation key. Later, this quote includes PCR value that will measure all components on the booting process, *CRTM*, *BIOS*, *boot loader*, *vmlinuz (kernel)*, *initramfs*, then RustMonitor (the hypervisor) completing the trust chain. Next, the actual enclave and the verification of the generated HyperEnclave certificate. In case of a remote attestation, the verifier receives the attestation report, and validates it by comparing both measurements of the booted code and the enclave against known values. And checking the certificate chain of both TPM quote and RustMonitor's signature.

Using *HyperEnclave* with BitTorrent swarms, leveraging its process based model, flexible privilege modes along with its hardware agnostic design could prove to be an interesting solution to for peer attestation. As explained earlier by running some parts of the BitTorrent components inside enclaves, such as: peer attestation, chunk integrity validation, among others, it could mitigate some of the attacks explained before. Although, current implementations are limited to the x86 architecture and doesn't support *ARM* or *RISC-V*, despite existing an active community interest in such extensions. Despite the limitations, *HyperEnclave* could still offer unified attestation framework across a full spectrum of BitTorrent swarm participants. As an open-source alternative that is fully auditable at any time, it represents an ideal foundation for an academic implementation of a custom, security enhanced BitTorrent client, enabling both client attestation between peers, testing client authenticity, chunk integrity checks. All of this, avoiding the dependence on strict proprietary hardware features, being platform agnostic.

Beyond HyperEnclave, there other academic and open source TEE implementations that tackle other aspects, that could enhance trust within BitTorrent swarms:

+ *Komodo* [cite, 35], implements an SGX like enclave protection model on TrustZone backend.

+ *Keystone* [cite, 49], another TEE that supports RISC-V platforms.

+ *Genode* [cite, 35] by Genode Labs

+ *Open-TEE* [cite, 47] by Intel Collaborative Research Institute for Secure Computing

+ *SafeG* [cite, 48] by Nagoya University

+ *ViMoExpress* [cite, 49] by Electronic and Telecommunication Research Institute

+ *TLR* [cite, 8] by Microsoft Research
