*** SafeKeeper: SGX-Based Password Protection with Client-Side Attestation

# (003, Some of them (e.g. [5, 11, 30]) make use of hardware-based trusted execution environments (TEEs) on the server side)

In this section, it will be reviewed some projects and implementations that are build upon the Trusted Execution Environments (TEEs) discussed earlier. The focus will not be the technical descriptions, but how each project usage the TEE capabilities. More precisely, how they implemented remote attestation, memory protection g, root of trust mechanisms, in order to address the security challenges in distributed environments. Also, discuss the potential relevance of these solutions on BitTorrent swarms, precisely how they can mitigate previously identified vulnerabilities.

SafeKeeper, proposed by [cite], it's a system designed to protect password confidentiality in web authentication against threat actors. Including malicious servers and sophisticated phishing attacks. At its core, SafeKeeper uses a server side password protection service that hashes user passwords before storing it, with the service isolated inside an Intel SGX enclave. Also, the client side application is implemented as a browser extension that performs the remote attestation to verify the server side SGX enclave authenticity, thus ensuring a server is running a secure enclave with SafeKeeper password protection service. Thus, securing a secure channel between both, client browser and server. This approach doesn't rely on other client-server protections, like TLS certificates, enabling them to identify what code will handle the password server side. Which means, that once the users recognize the SafeKeeper client side signaling, means that the server also supports SafeKeeper and is ensured their password confidentiality. Successfully protecting them against *compromised servers* or *phishing attacks*. As explained, this solutions leverages Intel SGX for *remote attestation*, by using SGX quote mechanism to verify that the *password hashing mechanisms* is running currently inside an enclave, and verifies this by providing cryptographic proof of its integrity and authenticity. Also, how is being executed inside an isolated environment, sensitive password hashing operations, can't be neither observed or access it by the server operating system, a possible hypervisor, or a malicious software, because the enclave ensures integrity and authenticity. Furthermore, Intel SGX relies on a *root of trust* and self signed attestation reports, through the IAS, guarantying that is a valid SGX in both ends.

Moreover, they handle *remote attestations* for browser by modifying the standard SGX protocol for the *0-round-trip attestation*. Where the browser requests a quote without authenticating to the enclave, using their custom *attestation proxy* it can cache the quote verification response from IAS to reduce latency. Thus, solving the TLS required from IAS to perform remote attestation, where the proxy handles it, so the browser doesn't need to authenticate to the enclave.

While *SafeKeeper* targets web authentication, trying to impede phishing attacks and malicious servers from capturing secrets. It's client side attestation model, focus on verifying code integrity being executed on the server side, which perfectly fits the BitTorrent threat model. Where a similar mechanisms could be implemented to only allow a client to connect to other swarm participant only if it was running a non unmodified BitTorrent client. Which could mitigate significantly *Sybil Attacks*, and identifying dishonest peers. Furthermore, if the swarm requires a PoW before a bootstrap node connects it to the rest of the swarm, the verifier (bootstrap node) could ensure that the PoW algorithm was running on an isolated enclave. Verifying the authenticity and integrity of the computed challenge.
