*** BITE: Privacy-Preserving Lightweight Clients using Trusted Execution
:PROPERTIES:
:CUSTOM_ID: bite
:END:

BITE, proposed in [cite], is a solution for the bitcoin lightweight client, that delegates most of the computational and storage require on full blockchain nodes. As the paper explains, Bitcoin offers a private way to issue payments without being tracker by a centralized authority. But it requires the bitcoin user to download and process the entire chain, which it can be infeasible in devices with limited resources, like mobile or embedded devices.

However, this delegations can leak critical information about the client's transactions, thus defeating the user privacy that the decentralized cryptocurrencies should guarantee. BITE address this, by using Trusted Execution Environments, leveraging Intel SGX enclaves that serve transaction confidentiality requests from clients, since *SGX* assures confidentiality and integrity to client requests. More precisely, a client needs to verify a transactions or check how much coins are associated with a user's address, it can connect over a full node which supports BITE service.

The lightweight client creates a secure channel with the enclave, performing the *remote attestation*. After the channel been establish between both peers, the client exchanges the address that it want to search. Than, the enclave is responsible to gather the required information from it's local stored blockchain or the Unspent Transactions Database (UTXO) giving it back to the client to be verified.

It's core idea is using attested enclaves on nodes with higher computational power in order to provide privacy, and verifiable responses to lightweight clients, which translates directly to BitTorrent, for mobile, embedded or low resources peers within a swarm. BITE, enables full blockchain node to run SGX enclaves that attest its code integrity, in order to verify if a transaction is valid, while without leaking unrelated data. Which means, a lightweight client, like a mobile device, could perform *remote attestation* against a BitTorrent *tracker* or DHT *bootstrap node*, to verify its honesty, guaranteeing that isn't a modified implementation.

While indeed BITE depends on *Intel SGX*, it's attestation outsourcing model is hardware agnostic. For instance, a future BitTorrent implementation could implement a similar model with other solutions, like *HyperEnclave* that could be used in both *Intel* and *AMD* could based servers. Additionally, for *Arm devices* WATZ could server as an interesting choice to provide web based BitTorrent implementations a way to integrate with this model. By contrast, other optimal solution would be the usage of both *Sanctum* and *Sanctuary*, two open source solutions that aim to support the rising RISC-V, and x86 architectures and *Arm architectures*, respectively. Further implementations could enable a framework that would leverage these TEE solutions to enable the full spectrum of BitTorrent participants, trying to mitigate dishonesty and try to achieve the BitTorrent reciprocity principle.
